---
sidebar: sidebar 
permalink: analyze-error-logs.html 
keywords: analyze error logs, errors, error severity, Microsoft SQL Server error logs, smart analysis, Agentic AI 
summary: データベースのワークロード ファクトリ内のエラー ログを分析します。 
---
= ワークロードファクトリーのエラーログを分析する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
スマート エラー ログ アナライザーを使用すると、Microsoft SQL Server のエラー ログを自動的に解釈して、問題を迅速に特定し解決することができます。  Agentic AI ベースの分析には、Amazon Bedrock の統合が必要です。

.タスクの内容
エラー ログの分析と修復は、SQL Server インスタンスの正常性とパフォーマンスの維持に役立ちます。 SQL Server エラー ログを効果的に解釈するには、慎重な分析と専門知識が必要です。手動による監視、エラー検出、根本原因分析には時間がかかり、エラーが発生しやすくなります。これらの課題により、問題解決が遅れ、ダウンタイムが増加し、運用効率が低下する可能性があります。スマート エラー ログ アナライザーは、次のような主な利点によってこれらの課題に対処します。

* スマートなグループ化: エラーを一意性、重大度、カテゴリ別にインテリジェントに統合し、トラブルシューティング プロセスを簡素化して、より迅速かつ効果的な解決を実現します。
* AI 主導の調査: AI を活用してエラーをプロアクティブに分析し、明確で実用的な洞察を提供することで、深い専門知識を必要とせずに問題の特定を加速します。
* エラーの強化: 外部参照を使用してエラー ログを強化し、コンテキストを明確にすることで、理解と意思決定を向上させます。
* ベスト プラクティスの修復: FSx for ONTAPで実行されている SQL Server ワークロードに合わせてカスタマイズされた修復推奨事項を提供し、あらゆるスキル レベルのユーザーが自信を持って問題を解決できるようにします。


スマート エラー ログ アナライザーを使用すると、高度な AI 分析のメリットを活用しながら、環境を完全に制御できます。

スマート エラー ログ アナライザーを使用するには、Amazon Bedrock をアクティブ化し、モデル ワークロード ファクトリーが使用するモデルを選択し、Amazon Bedrock に接続するためのプライベート エンドポイントを作成し、アクセス許可を追加して、エンタープライズ ライセンスを作成する必要があります。

link:https://aws.amazon.com/bedrock/pricing/["Amazon Bedrockの価格"^]

.開始する前に
スマート エラー ログ アナライザーを使用するには、次の前提条件を満たしている必要があります。

* ワークロードファクトリで新しいデータベースホストを作成する必要がありlink:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWS アカウントの認証情報と読み取り/書き込みモードの権限"^]ます。
* link:https://docs.netapp.com/us-en/workload-databases/register-instance.html["SQL Server インスタンスを登録する"^]ワークロードファクトリー内。*


.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. [データベース]で、*[インベントリ]*タブを選択します。
. データベース エンジンとして *SQL Server* を選択します。
. [インスタンス] タブで、分析する特定の SQL Server インスタンスを見つけて、メニューから [エラーの調査] を選択します。
. *エラー調査* タブで、コンソールに説明されているように次の前提条件を完了します。
+
** アマゾンの岩盤
** ネットワーキング: Amazon Bedrock のプライベートエンドポイント
** EC2インスタンスプロファイルロールの権限
** ワークロード データベース管理 (wlmdb) に関連付けられた資格情報


. 前提条件が満たされている場合は、[今すぐ調査] を選択して、スマート エラー ログ アナライザーを使用して SQL Server エラー ログの詳細を取得します。
+
スキャン後、コンソールにエラーが表示され、スマート エラー ログ アナライザーによって検出された問題の包括的なビューが提供されます。

. フィルターを使用して、重大度、期間、エラー コードなどの基準に基づいて、表示されるエラーを絞り込みます。
. 元のエラー メッセージ、AI ベースの説明、エラーを解決するための推奨される修復手順など、詳細なエラー情報を確認します。

