---
sidebar: sidebar 
permalink: create-sandbox-clone.html 
keywords: create, clone, sandbox 
summary: NetApp Workload Factory for Databases でサンドボックス クローンを作成します。 
---
= NetApp Workload Factory for Databases でサンドボックス クローンを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory for Databases でデータベースのサンドボックス クローンを作成すると、ソース データベースを変更することなく、開発、テスト、統合、分析、トレーニング、QA などにクローンを使用できます。

.タスクの内容
サンドボックスクローンは、ソースデータベースの最新のSnapshotから作成されます。ソースデータベースと同じMicrosoft SQL Serverでクローニングすることも、別のMicrosoft SQL Serverでクローニングすることもできます。ただし、同じFSx for ONTAPファイルシステムを共有している必要があります。

.開始する前に
サンドボックスクローンを作成する前に、次の前提条件を満たしていることを確認してください。

* *資格情報と権限*: 必要なのはlink:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWS アカウントの認証情報と _読み取り専用_ または _読み取り/書き込み_ モードの権限"^]Workload Factory でサンドボックス クローンを作成します。
+
あるいは、Codebox を使用して部分的に完了したテンプレートをコピーしたり、完了したテンプレートを作成して、REST API を使用して Workload Factory の外部でサンドボックス クローンを作成することもできます。link:https://docs.netapp.com/us-en/workload-setup-admin/codebox-automation.html["Codebox自動化の詳細"^] 。

* *Microsoft SQL Server*: 新しいサンドボックス クローンをホストするには、Workload Factory for Databases に管理された Microsoft SQL Server が必要です。
* *AWSシステムマネージャー*: `NT Authority\SYSTEM` AWS Systems Manager を介して Microsoft SQL ホストでユーザー権限が有効になります。
* *ソース データベース*: クローンにはソース データベースが使用可能である必要があります。


.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. [データベース]で、[サンドボックス]タブを選択します。
. [サンドボックス]タブで、*[新しいサンドボックスの作成]*を選択します。
. [Create new sandbox]ページの[Database source]で、次の情報を指定します。
+
.. *ソースデータベースホスト*：ソースデータベースホストを選択します。
.. *ソースデータベースインスタンス*:ソースデータベースインスタンスを選択します。
.. *ソースデータベース*：クローニング元のソースデータベースを選択します。


. [データベースターゲット]で、次の情報を入力します。
+
.. *ターゲットデータベースホスト*：同じVPC内にあり、ソースホストと同じFSx for ONTAPファイルシステムを持つサンドボックスクローンのターゲットデータベースホストを選択します。
.. *ターゲットデータベースインスタンス*：サンドボックスクローンのターゲットデータベースインスタンスを選択します。
.. *ターゲットデータベース*：サンドボックスクローンの名前を入力します。


. *マウント*: 複数のデータ ファイルやログ ファイルを持つ SQL データベースのクローンを作成する場合、Workload Factory は、自動的に割り当てられた、または定義されたドライブ文字の下にあるすべてのファイルをクローンします。
+
次のいずれかのオプションを選択します。

+
.. *マウントポイントの自動割り当て*
.. *マウントポイントパスの定義*
+
以下を指定してマウントポイントパスを定義します。

+
*** データファイルパスのドライブ文字を入力します。
*** ログファイルパスのドライブレターを入力します。




. *タグを定義*：サンドボックスクローンを定義するタグを選択します。
. [ 作成（ Create ） ] をクリックします。


ジョブの進行状況を確認するには、*ジョブ監視*タブに移動します。
