---
sidebar: sidebar 
permalink: create-postgresql-server.html 
keywords: create, server, PostgreSQL, deploy, host, deploy a database host, database host 
summary: データベース用のBlueXP  ワークロードファクトリ内に新しいPostgreSQLサーバを作成します。 
---
= BlueXP  ワークロードファクトリでPostgreSQLサーバを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  Workload Factory for Databasesで新しいPostgreSQLサーバ（データベースホスト）を作成するには、FSx for ONTAPファイルシステムの導入とActive Directory用のリソースが必要です。

.タスクの内容
AWSアカウントのクレデンシャルと_automate_permissionsが必要です。

作業を開始する前に、データベースホストの構成で使用可能なストレージ導入タイプ、Active Directoryの導入、ワークロードの工場出荷時の動作モード、およびこの処理を完了するための要件について学習します。

FSx for ONTAPファイルシステムの導入:: 新しいPostgreSQLサーバを作成するには、ストレージバックエンドとしてFSx for ONTAPファイルシステムが必要です。FSx for ONTAPの既存のファイルシステムを使用することも、新しいファイルシステムを作成することもできます。データベースサーバのストレージバックエンドとして既存のFSx for ONTAPファイルシステムを選択した場合は、PostgreSQLワークロード用の新しいStorage VMを作成します。


FSx for ONTAPファイルシステムは、PostgreSQLの_standalone_deploymentsをサポートしています。ワークロード工場では、データ、ログ、tempdbファイル用のボリュームとLUNに加えて、単一のアベイラビリティゾーンFSx for ONTAPファイルシステムが作成されています。

ワークロードファクトリ動作モード:: Workload Factoryには、ワークロードファクトリがAWSリソースを管理できるようにする方法に応じて、3つの運用モードが用意されています。


*_Basic_mode *：この操作モードでは、ワークロードファクトリにAWSアカウントのクレデンシャルを関連付ける必要はありません。部分的に塗りつぶされたYAMLテンプレートをコードボックスからコピーまたはダウンロードして、ワークロードファクトリの外で完成させることができます。

*_Read_mode *:この操作モードでは、AWSアカウントのクレデンシャルに読み取り権限を付与します。これにより、_Quick create_or_Advanced create_formを完成させ、コピーまたはダウンロードすることができます。入力したフォームの詳細を使用して、ワークロードファクトリからCloudFormationにリダイレクトすることもできます。また、ワークロードファクトリに導入されたデータベースサーバを管理できるようになります。

*_automate_mode *：この操作モードでは、AWSアカウントのクレデンシャルに自動化権限を付与します。これにより、ワークロードファクトリ内でAWSリソースを作成および管理できます。

.開始する前に
新しいデータベースホストを作成する前に、次の前提条件を満たしていることを確認してください。

クレデンシャルと権限:: ワークロードファクトリで新しいデータベースホストを作成する必要がありlink:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWSアカウントのクレデンシャルと自動モードの権限"^]ます。
+
--
または、Codeboxを使用して空のテンプレートをコピーするか、完成したテンプレートを作成して、REST API、AWS CLI、またはAWS CloudFormationを使用してワークロードファクトリの外部にデータベースを導入できます。link:https://docs.netapp.com/us-en/workload-setup-admin/codebox-automation.html["Codebox自動化の詳細"^]です。

--




== データベースサーバの作成

このタスクは、_Quick create_or_Advanced create_deploymentモードを使用して、_automate_mode権限でワークロードファクトリで実行できます。また、Codeboxで利用可能なREST APIおよびCloudFormationツールを使用することもできます。link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["Codeboxを使用して自動化する方法"^]です。

+

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで*[データベースホストの配置]*を選択し、ドロップダウンメニューから*[PostgreSQL]*を選択します。
. [詳細作成]*を選択します。
. 導入モデル*の場合、*スタンドアロンインスタンス*がデフォルトです。
. [AWS settings]*で、次の情報を指定します。
+
.. * AWSクレデンシャル*：自動化権限を持つAWSクレデンシャルを選択して、新しいデータベースホストを導入します。
+
_automate_permissionsを指定したAWSクレデンシャルを使用すると、ワークロードファクトリ内のAWSアカウントから新しいデータベースホストを導入して管理できます。

+
AWSクレデンシャルに_read_permissionsを指定すると、ワークロードファクトリでCloudFormationテンプレートが生成され、AWS CloudFormationコンソールで使用できます。

+
ワークロードファクトリにAWSクレデンシャルが関連付けられておらず、ワークロードファクトリに新しいサーバを作成する場合は、*オプション1 *に従って[クレデンシャル]ページに移動します。データベースワークロードの_automate_modeに必要なクレデンシャルと権限を手動で追加します。

+
AWS CloudFormationで展開するための完全なYAMLファイルテンプレートをダウンロードできるように、ワークロードファクトリで新しいサーバーの作成フォームに入力する場合は、*オプション2 *に従って、AWS CloudFormation内で新しいサーバーを作成するために必要な権限を持っていることを確認します。データベースワークロードの_read_modeに必要なクレデンシャルと権限を手動で追加します。

+
必要に応じて、部分的に完成したYAMLファイルテンプレートを[コードボックス]からダウンロードして、資格情報や権限なしでワークロードファクトリの外部にスタックを作成できます。[コードボックス]のドロップダウンから[CloudFormation]*を選択して、YAMLファイルをダウンロードします。

.. *リージョンとVPC *：リージョンとVPCネットワークを選択します。
+
既存のインターフェイスエンドポイントのセキュリティグループが、選択したサブネットへのHTTPS（443）プロトコルへのアクセスを許可するようにします。

+
AWSサービスインターフェイスエンドポイント（SQS、FSx、EC2、CloudWatch、Cloud Formation、 SSM）とS3ゲートウェイエンドポイントが見つからない場合は、導入時に作成されます。

+
vPC DNS属性 `EnableDnsSupport` とが `EnableDnsHostnames` 、エンドポイントアドレス解決を有効にするように変更されます（まだに設定されていない場合） `true`。

.. *アベイラビリティゾーン*：アベイラビリティゾーンとサブネットを選択します。
+
単一インスタンス環境向け::
+
--
... [クラスタ構成-ノード1 ]*フィールドで、*[アベイラビリティゾーン]*ドロップダウンメニューからアベイラビリティゾーンを選択し、*[サブネット]*ドロップダウンメニューからサブネットを選択します。


--


.. *セキュリティグループ*:既存のセキュリティグループを選択するか、新しいセキュリティグループを作成します。
+
新しいサーバの導入時に、2つのセキュリティグループがSQLノード（EC2インスタンス）に接続されます。

+
... PostgreSQLに必要なポートとプロトコルを許可するために、ワークロードセキュリティグループが作成されます。
... 既存のFSx for ONTAPファイルシステムでは、関連付けられているセキュリティグループがPostgreSQLノードに自動的に追加され、ファイルシステムとの通信が可能になります。新しいFSx for ONTAPシステムが作成されると、FSx for ONTAPファイルシステム用の新しいセキュリティグループが作成され、同じセキュリティグループがSQLノードに接続されます。




. [アプリケーションの設定]*で、次の情報を入力します。
+
.. ドロップダウン・メニューから*[Operating system]*を選択します。
.. ドロップダウンメニューから* PostgreSQLバージョン*を選択します。
.. *データベースサーバ名*：データベースクラスタ名を入力します。
.. *データベース資格情報*：新しいサービスアカウントのユーザー名とパスワードを入力するか、Active Directoryの既存のサービスアカウント資格情報を使用します。


. [Connectivity]*で、インスタンスに安全に接続するキーペアを選択します。
. [インフラストラクチャー設定]*で、次の情報を入力します。
+
.. * DBインスタンスタイプ*：ドロップダウン・メニューからデータベース・インスタンス・タイプを選択します。
.. * FSx for ONTAPシステム*：新しいFSx for ONTAPファイルシステムを作成するか、既存のFSx for ONTAPファイルシステムを使用します。
+
... *新しいFSx for ONTAPを作成*：ユーザー名とパスワードを入力します。
+
新しいFSx for ONTAPファイルシステムでは、インストールに30分以上かかる場合があります。

... *既存のFSx for ONTAPを選択*：ドロップダウンメニューからFSx for ONTAP名を選択し、ファイルシステムのユーザ名とパスワードを入力します。
+
既存のFSx for ONTAPファイルシステムについては、次の点を確認します。

+
**** FSx for ONTAPに関連付けられたルーティンググループを使用すると、サブネットへのルートを導入に使用できるようになります。
**** セキュリティグループは、導入に使用されるサブネット、特にHTTPS（443）とiSCSI（3260）のTCPポートからのトラフィックを許可します。




.. * Snapshotポリシー*：デフォルトで有効になっています。Snapshotは毎日作成され、保持期間は7日間です。
+
Snapshotは、PostgreSQLワークロード用に作成されたボリュームに割り当てられます。

.. *データドライブサイズ*：データドライブの容量を入力し、容量単位を選択します。
.. *[Provisioned IOPS]*：*[Automatic]*または*[User-Provisioned]*を選択します。[User-Provisioned]*を選択した場合は、IOPS値を入力します。
.. *スループット容量*：ドロップダウンメニューからスループット容量を選択します。
+
一部の地域では、4Gbpsのスループット容量を選択できます。4Gbpsのスループット容量をプロビジョニングするには、FSx for ONTAPファイルシステムが、少なくとも5、120GiBのSSDストレージ容量と16、000 IOPSで構成されている必要があります。

.. *暗号化*：アカウントからキーを選択するか、別のアカウントからキーを選択します。別のアカウントの暗号化キーARNを入力する必要があります。
+
FSx for ONTAPのカスタム暗号化キーは、サービスの適用性に応じて表示されません。適切なFSx暗号化キーを選択します。FSx以外の暗号化キーを使用すると、サーバの作成に失敗します。

+
AWSで管理されるキーは、サービスの適用可能性に基づいてフィルタリングされます。

.. *タグ*:オプションで、最大40個のタグを追加できます。
.. * Simple Notification Service *：必要に応じて、ドロップダウンメニューからMicrosoft SQL ServerのSNSトピックを選択して、この構成のSimple Notification Service（SNS）を有効にすることができます。
+
... Simple Notification Serviceを有効にします。
... ドロップダウンメニューからARNを選択します。


.. *CloudWatchの監視*:必要に応じて、CloudWatchの監視を有効にすることができます。
+
失敗した場合のデバッグ用にCloudWatchを有効にすることをお勧めします。AWS CloudFormationコンソールに表示されるイベントは高レベルであり、根本原因を特定するものではありません。すべての詳細ログは、EC2インスタンスのフォルダに保存され `C:\cfn\logs` ます。

+
CloudWatchでは、スタックの名前でロググループが作成されます。すべての検証ノードとSQLノードのログストリームがロググループの下に表示されます。CloudWatchには、スクリプトの進行状況が表示され、導入が失敗した場合とそのタイミングを理解するのに役立つ情報が提供されます。

.. *リソースロールバック*:この機能は現在サポートされていません。


. 概要
+
.. *推定コスト*：表示されているリソースを導入した場合に発生する可能性のある料金の見積もりを提供します。


. [作成]*をクリックして、新しいデータベースホストを導入します。
+
または、設定を保存することもできます。



.次のステップ
できるようになりまし link:create-database.html["BlueXP  ワークロードファクトリでデータベース用のデータベースを作成"]た。
