---
sidebar: sidebar 
permalink: create-sandbox-clone.html 
keywords: create, clone, sandbox 
summary: Workload Factory for Databasesでサンドボックスクローンを作成します。 
---
= Workload Factoryでデータベース用のサンドボックスクローンを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory for Databasesでデータベースのサンドボックスクローンを作成すると、クローンを開発、テスト、統合、分析、トレーニング、 QAなど、ソースデータベースを変更する必要はありません。

.タスクの内容
サンドボックスクローンは、ソースデータベースの最新のSnapshotから作成されます。ソースデータベースと同じMicrosoft SQL Serverでクローニングすることも、別のMicrosoft SQL Serverでクローニングすることもできます。ただし、同じFSx for ONTAPファイルシステムを共有している必要があります。

.開始する前に
サンドボックスクローンを作成する前に、次の前提条件を満たしていることを確認してください。

クレデンシャルと権限:: Workload Factoryでサンドボックスクローンを作成する必要があり link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWSアカウントのクレデンシャルと_read_or_automate_mode権限"^] ます。
+
--
または、[コードボックス]を使用して部分的に完成したテンプレートをコピーしたり、完成したテンプレートを作成して、REST APIを使用してWorkload Factoryの外部でサンドボックスクローンを作成したりすることもできます。link:https://docs.netapp.com/us-en/workload-setup-admin/codebox-automation.html["Codebox自動化の詳細"^]です。

--
Microsoft SQL Server:: 新しいサンドボックスクローンをホストするには、Workload Factory for Databasesに管理対象のMicrosoft SQL Serverが必要です。
AWSシステムマネージャ:: AWS Systems Managerを使用してMicrosoft SQLホストでユーザ権限が有効になっていることを確認します `NT Authority\SYSTEM` 。
ソースデータベース:: クローンに使用できるソースデータベースが必要です。


.手順
. にログインし link:https://console.workloads.netapp.com["Workload Factoryコンソール"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. [データベース]で、[サンドボックス]タブを選択します。
. [サンドボックス]タブで、*[新しいサンドボックスの作成]*を選択します。
. [Create new sandbox]ページの[Database source]で、次の情報を指定します。
+
.. *ソースデータベースホスト*：ソースデータベースホストを選択します。
.. *ソースデータベースインスタンス*:ソースデータベースインスタンスを選択します。
.. *ソースデータベース*：クローニング元のソースデータベースを選択します。


. [データベースターゲット]で、次の情報を入力します。
+
.. *ターゲットデータベースホスト*：同じVPC内にあり、ソースホストと同じFSx for ONTAPファイルシステムを持つサンドボックスクローンのターゲットデータベースホストを選択します。
.. *ターゲットデータベースインスタンス*：サンドボックスクローンのターゲットデータベースインスタンスを選択します。
.. *ターゲットデータベース*：サンドボックスクローンの名前を入力します。


. *マウント*：複数のデータファイルやログファイルを含むSQLデータベースをクローニングする場合、Workload Factoryは自動割り当てまたは定義されたドライブレターの下にあるすべてのファイルをクローニングします。
+
次のいずれかのオプションを選択します。

+
.. *マウントポイントの自動割り当て*
.. *マウントポイントパスの定義*
+
以下を指定してマウントポイントパスを定義します。

+
*** データファイルパスのドライブ文字を入力します。
*** ログファイルパスのドライブレターを入力します。




. *タグを定義*：サンドボックスクローンを定義するタグを選択します。
. [ 作成（ Create ） ] をクリックします。


ジョブの進行状況を確認するには、*ジョブ監視*タブに移動します。
