---
sidebar: sidebar 
permalink: create-database.html 
keywords: create, database, creation, Microsoft SQL 
summary: NetApp Workload Factory for Databases を使用して Microsoft SQL データベースを作成します。 
---
= NetApp Workload Factory for Databases で Microsoft SQL データベースを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
新しい Microsoft SQL データベースを作成すると、 NetApp Workload Factory for Databases 内でリソースを管理できるようになります。

.タスクの内容
データベースを作成すると、独立したLUNで構成されるFSx for ONTAPファイルシステムに2つのボリュームが作成され、データベースのデータファイルとログファイルをホストします。新しいデータベース内のデータベースファイルはシンプロビジョニングされ、新しいデータベースに割り当てられた合計サイズのわずか数MBしか消費しません。

データベースのストレージを分離する場合は、_ virtualマウントポイント_を使用します。仮想マウントポイントを使用すると、ホスト上のいくつかの共通ドライブにデータベースを統合できます。

ワークロード ファクトリーでデータベースを作成するには、_表示、計画、および分析_ の権限が必要です。あるいは、部分的に完了したコード テンプレートをコピーまたはダウンロードして、ワークロード ファクトリー外で操作を完了することもできます。link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["ワークロードファクトリーの権限について学ぶ"^] 使用するモードを決定します。


NOTE: SMBプロトコルを使用するMicrosoft SQL Serverでは、データベースの作成はサポートされていません。

.開始する前に
新しいデータベースを作成する前に、次の前提条件を満たしていることを確認してください。

* *資格情報と権限*: 必要なのは link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWS アカウントの認証情報と _表示、計画、分析_ の権限"^] Workload Factory に新しいデータベースを作成します。
+
または、[コードボックス]を使用してテンプレートをコピーし、REST APIを使用してワークロードファクトリの外部にデータベースを導入することもできます。link:https://docs.netapp.com/us-en/workload-setup-admin/codebox-automation.html["Codebox自動化の詳細"^]です。

* *Windows ホスト*: _クイック作成_ モードを使用する場合は、新しいデータベース用の新しいドライブを作成するために、Microsoft SQL Server で十分なドライブ文字が必要です。
* *Microsoft SQL Server*: 新しいデータベースをホストするには、データベースのワークロード ファクトリに管理された Microsoft SQL Server が必要です。
* *AWSシステムマネージャー*: `NT Authority\SYSTEM` AWS Systems Manager を介して Microsoft SQL ホストでユーザー権限が有効になります。




== データベースの作成

Workload Factory でこのタスクを完了するには、_クイック作成_ または _詳細作成_ のデプロイメント モードを使用できます。

[role="tabbed-block"]
====
.クイック作成
--
.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. データベース メニューから、*インベントリ* を選択します。
. インベントリで、データベース エンジンの種類として *Microsoft SQL Server* を選択します。
. データベースを作成するための、管理された SQL サーバー インスタンスを持つデータベース サーバーを選択します。
. マネージドインスタンスのアクション メニューをクリックし、*ユーザー データベースの作成*を選択します。
. [Create user database]ページの[Database information]で、次の情報を指定します。
+
.. *データベース名*：データベースの名前を入力します。
.. *Collation*:データベースの照合を選択します。Microsoft SQL Serverのデフォルト照合SQL_Latin1_General_CP1_CI_ASが選択されています


. [ファイルの設定]で、次の情報を入力します。
+
.. *ファイル設定モード*：*クイック作成*を選択します。
.. *ファイル名とパス*:
+
*** *データファイル名*:データファイル名を入力します。
*** *ログファイル名*:ログファイル名を入力します。


.. *ファイルサイズ*：データベースのデータサイズとログサイズを入力します。


. [ 作成（ Create ） ] をクリックします。
+
または、これらのデフォルト設定のいずれかを今すぐ変更する場合は、*ファイル設定モード*を*詳細作成*に変更します。



--
.高度な作成
--
.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. データベース メニューから、*インベントリ* を選択します。
. インベントリで、データベース エンジンの種類として *Microsoft SQL Server* を選択します。
. データベースを作成するための、管理された SQL サーバー インスタンスを持つデータベース サーバーを選択します。
. マネージドインスタンスのアクション メニューをクリックし、*ユーザー データベースの作成*を選択します。
. [ユーザーデータベースの作成]*を選択します。
. [Create user database]ページの[Database information]で、次の情報を指定します。
+
.. *データベース名*：データベースの名前を入力します。
.. *Collation*:データベースの照合を選択します。Microsoft SQL Serverのデフォルト照合SQL_Latin1_General_CP1_CI_ASが選択されています


. [ファイルの設定]で、次の情報を入力します。
+
.. *ファイル設定モード*：*詳細作成*を選択します。
.. *ファイル名とパス*:
+
... *データファイル*:ドライブ文字を選択し、データファイル名を入力します。
+
必要に応じて、*[Virtual mount point]*のボックスをクリックします。

... *ログファイル*:ドライブ文字を選択し、ログファイル名を入力します。
+
必要に応じて、*[Virtual mount point]*のボックスをクリックします。



.. *ファイルサイズ*：データベースのデータサイズとログサイズを入力します。


. [ 作成（ Create ） ] をクリックします。


--
====
データベースホストを作成した場合は、*[ジョブ監視]*タブでジョブの進行状況を確認できます。
