---
sidebar: sidebar 
permalink: create-database.html 
keywords: create, database, creation, Microsoft SQL 
summary: データベース用のBlueXP  ワークロードファクトリを備えたMicrosoft SQLデータベースを作成します。 
---
= BlueXP  ワークロードファクトリでデータベース用のMicrosoft SQLデータベースを作成
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
新しいMicrosoft SQLデータベースを作成すると、データベースのBlueXP  ワークロードファクトリ内でリソースを管理できるようになります。

.タスクの内容
データベースを作成すると、独立したLUNで構成されるFSx for ONTAPファイルシステムに2つのボリュームが作成され、データベースのデータファイルとログファイルをホストします。新しいデータベース内のデータベースファイルはシンプロビジョニングされ、新しいデータベースに割り当てられた合計サイズのわずか数MBしか消費しません。

データベースのストレージを分離する場合は、_ virtualマウントポイント_を使用します。仮想マウントポイントを使用すると、ホスト上のいくつかの共通ドライブにデータベースを統合できます。

ワークロードファクトリでデータベースを作成するには、自動モードの権限が必要です。または、基本モードでは、部分的に完了したコードテンプレートをコピーまたはダウンロードして、ワークロードファクトリ外での操作を完了できます。link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html["ワークロードファクトリの運用モードの詳細"^] 使用するモードを決定します。


NOTE: SMBプロトコルを使用するMicrosoft SQL Serverでは、データベースの作成はサポートされていません。

.開始する前に
新しいデータベースを作成する前に、次の前提条件を満たしていることを確認してください。

クレデンシャルと権限:: ワークロードファクトリで新しいデータベースを作成する必要がありlink:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWS アカウントの認証情報と _読み取り専用_ または _読み取り/書き込み_ モードの権限"^]ます。
+
--
または、[コードボックス]を使用してテンプレートをコピーし、REST APIを使用してワークロードファクトリの外部にデータベースを導入することもできます。link:https://docs.netapp.com/us-en/workload-setup-admin/codebox-automation.html["Codebox自動化の詳細"^]です。

--
Windowsホスト:: _Quick create_modeを使用する場合は、新しいデータベース用の新しいドライブを作成するために、Microsoft SQL Serverに十分な数のドライブレターが必要です。
Microsoft SQL Server:: データベースで新しいデータベースをホストするには、管理対象のMicrosoft SQL Serverがワークロードファクトリにある必要があります。
AWSシステムマネージャ:: AWS System Managerを使用してMicrosoft SQLホストで権限が有効になっていることを確認します `NT Authority\SYSTEM user` 。




== データベースの作成

_クイック作成_ または _詳細作成_ のデプロイメント モードを使用して、_読み取り専用_ または _読み取り/書き込み_ モードの権限でワークロード ファクトリでこのタスクを完了できます。

[role="tabbed-block"]
====
.クイック作成
--
.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. [データベース]で、*[インベントリ]*タブを選択します。
. [インベントリ]タブで、データベースを作成する管理対象SQLサーバーインスタンスを持つデータベースサーバーを選択します。
. 管理対象インスタンスの 3 つのドット メニューをクリックし、*ユーザー データベースの作成* を選択します。
. [Create user database]ページの[Database information]で、次の情報を指定します。
+
.. *データベース名*：データベースの名前を入力します。
.. *Collation*:データベースの照合を選択します。Microsoft SQL Serverのデフォルト照合SQL_Latin1_General_CP1_CI_ASが選択されています


. [ファイルの設定]で、次の情報を入力します。
+
.. *ファイル設定モード*：*クイック作成*を選択します。
.. *ファイル名とパス*:
+
*** *データファイル名*:データファイル名を入力します。
*** *ログファイル名*:ログファイル名を入力します。


.. *ファイルサイズ*：データベースのデータサイズとログサイズを入力します。


. [ 作成（ Create ） ] をクリックします。
+
または、これらのデフォルト設定のいずれかを今すぐ変更する場合は、*ファイル設定モード*を*詳細作成*に変更します。



--
.高度な作成
--
.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. [データベース]で、*[インベントリ]*タブを選択します。
. [インベントリ]タブで、データベースを作成する管理対象SQLサーバーインスタンスを持つデータベースサーバーを選択します。
. 管理対象インスタンスの3ドットのメニューをクリックし、* Create user database *を選択します。
. [ユーザーデータベースの作成]*を選択します。
. [Create user database]ページの[Database information]で、次の情報を指定します。
+
.. *データベース名*：データベースの名前を入力します。
.. *Collation*:データベースの照合を選択します。Microsoft SQL Serverのデフォルト照合SQL_Latin1_General_CP1_CI_ASが選択されています


. [ファイルの設定]で、次の情報を入力します。
+
.. *ファイル設定モード*：*詳細作成*を選択します。
.. *ファイル名とパス*:
+
... *データファイル*:ドライブ文字を選択し、データファイル名を入力します。
+
必要に応じて、*[Virtual mount point]*のボックスをクリックします。

... *ログファイル*:ドライブ文字を選択し、ログファイル名を入力します。
+
必要に応じて、*[Virtual mount point]*のボックスをクリックします。



.. *ファイルサイズ*：データベースのデータサイズとログサイズを入力します。


. [ 作成（ Create ） ] をクリックします。


--
====
データベースホストを作成した場合は、*[ジョブ監視]*タブでジョブの進行状況を確認できます。
