---
sidebar: sidebar 
permalink: create-sandbox-clone.html 
keywords: create, clone, sandbox 
summary: BlueXP  ワークロードファクトリでデータベース用のサンドボックスクローンを作成します。 
---
= BlueXP  ワークロードファクトリでデータベース用のサンドボックスクローンを作成
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  Workload Factory for Databasesでデータベースのサンドボックスクローンを作成すると、ソースデータベースを変更することなく、そのクローンを開発、テスト、統合、分析、トレーニング、QAなどに使用できます。

.タスクの内容
サンドボックスクローンは、ソースデータベースの最新のSnapshotから作成されます。ソースデータベースと同じMicrosoft SQL Serverでクローニングすることも、別のMicrosoft SQL Serverでクローニングすることもできます。ただし、同じFSx for ONTAPファイルシステムを共有している必要があります。

.開始する前に
サンドボックスクローンを作成する前に、次の前提条件を満たしていることを確認してください。

クレデンシャルと権限:: ワークロードファクトリでサンドボックスクローンを作成する必要がありlink:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWS アカウントの認証情報と _読み取り専用_ または _読み取り/書き込み_ モードの権限"^]ます。
+
--
または、[コードボックス]を使用して部分的に完成したテンプレートをコピーするか、完成したテンプレートを作成して、REST APIを使用してワークロードファクトリの外部にサンドボックスクローンを作成できます。link:https://docs.netapp.com/us-en/workload-setup-admin/codebox-automation.html["Codebox自動化の詳細"^]です。

--
Microsoft SQL Server:: データベースで新しいサンドボックスクローンをホストするには、管理対象のMicrosoft SQL Serverがワークロードファクトリにある必要があります。
AWSシステムマネージャ:: AWS Systems Managerを使用してMicrosoft SQLホストでユーザ権限が有効になっていることを確認します `NT Authority\SYSTEM` 。
ソースデータベース:: クローンに使用できるソースデータベースが必要です。


.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. [データベース]で、[サンドボックス]タブを選択します。
. [サンドボックス]タブで、*[新しいサンドボックスの作成]*を選択します。
. [Create new sandbox]ページの[Database source]で、次の情報を指定します。
+
.. *ソースデータベースホスト*：ソースデータベースホストを選択します。
.. *ソースデータベースインスタンス*:ソースデータベースインスタンスを選択します。
.. *ソースデータベース*：クローニング元のソースデータベースを選択します。


. [データベースターゲット]で、次の情報を入力します。
+
.. *ターゲットデータベースホスト*：同じVPC内にあり、ソースホストと同じFSx for ONTAPファイルシステムを持つサンドボックスクローンのターゲットデータベースホストを選択します。
.. *ターゲットデータベースインスタンス*：サンドボックスクローンのターゲットデータベースインスタンスを選択します。
.. *ターゲットデータベース*：サンドボックスクローンの名前を入力します。


. *マウント*：複数のデータファイルやログファイルを含むSQLデータベースをクローニングする場合、ワークロード工場では、自動割り当てまたは定義されたドライブレターの下にあるすべてのファイルのクローンが作成されます。
+
次のいずれかのオプションを選択します。

+
.. *マウントポイントの自動割り当て*
.. *マウントポイントパスの定義*
+
以下を指定してマウントポイントパスを定義します。

+
*** データファイルパスのドライブ文字を入力します。
*** ログファイルパスのドライブレターを入力します。




. *タグを定義*：サンドボックスクローンを定義するタグを選択します。
. [ 作成（ Create ） ] をクリックします。


ジョブの進行状況を確認するには、*ジョブ監視*タブに移動します。
