---
sidebar: sidebar 
permalink: detect-host.html 
keywords: detect, detect server instance, instance, detect a database host, instance 
summary: データベース用のBlueXP  ワークロードファクトリでMicrosoft SQL Serverインスタンスを検出します。 
---
= Microsoft SQL Serverインスタンスの検出
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
データベース用のBlueXP  ワークロードファクトリでMicrosoft SQL Serverインスタンスを検出します。

このタスクでは、_undetectedインスタンス_を検出します。

.タスクの内容
AWSクレデンシャルがワークロードファクトリに関連付けられている場合、データベースでは、次のAWSストレージタイプを使用したSQL Server 2016以降のMicrosoft SQL Serverの自動検出が可能になります。

* FSX for ONTAP の略
* Elastic Block Store（EBS）
* FSx for Windowsファイルサーバ


データベースでは、検出されたインスタンスは次のように分類されます。

* _検出されないインスタンス_：ワークロードファクトリによって自動的に検出された検出されないインスタンス。次の場合、インスタンスは検出されません。
+
** Microsoft SQL Server認証に失敗します。
** Microsoft SQL Server向けFSx for ONTAPファイルシステムは、ワークロード工場のお客様のアカウントに登録されていません。


* _管理対象外インスタンス_：ワークロードファクトリで管理されていないインスタンスを検出しました
* _管理対象インスタンス_：Workload Factoryで管理されているインスタンスを検出しました。


データベースのワークロードファクトリでMicrosoft SQL Serverインスタンス（ホストインスタンス）を管理するための最初のステップは、検出されていないデータベースサーバインスタンスを検出することです。

.開始する前に
検出されていないデータベースサーバインスタンスを検出するための要件は次のとおりです。

* ワークロードファクトリでデータベースサーバインスタンスを検出する必要がありlink:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWSアカウントノクレデンシャル"^]ます。
* インスタンスのストレージタイプは次のいずれかである必要があります。
+
** FSX for ONTAP の略
** Elastic Block Store（EBS）
** FSx for Windowsファイルサーバ


* EC2インスタンスには、SSM接続による検出を可能にするロール/インスタンスプロファイルが必要です。
+
Microsoft SQLインスタンスが検出されても、既存の環境は変更されません。検出はAWS Systems Manager Session Manager（SSM）を介して行われます。適切なIAMインスタンスプロファイルがないと、検出に失敗します。link:https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-troubleshooting.html["SSMのトラブルシューティングの詳細"^]です。



.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. [データベース]で、*[インベントリ]*タブを選択します。
. ドロップダウン矢印をクリックして、検出するホストの行を展開します。
+
ホストが展開され、ホストインスタンスが表示されます。

. 検出するインスタンスの3つのドットメニューをクリックします。
. [検出]*をクリックします。
. [インスタンスの検出]ダイアログで、Microsoft SQL Serverのユーザー名とパスワード、またはFSx for ONTAPのユーザー名とパスワードを入力します。
+
ワークロードファクトリでは、Microsoft SQLのクレデンシャルまたはFSx for ONTAPのクレデンシャルが検証されます。

+
これらの資格情報のいずれかが使用できない場合、Workload FactoryはPowerShellにモジュールをインストールしようとし `aws.tools.SimpleSystemsManagement`ます。

. [検出]*をクリックします。
+
検出されたインスタンス情報が表示されます

. [Yes、Manage instance via Workload Factory]*または*[No]*を選択します。
. [ 完了（ Done ） ] をクリックします。


.次のステップ
ホストインスタンスのストレージタイプがFSx for ONTAPの場合は可能です link:manage-server.html["Workload Factory経由でインスタンスを管理"]。
