---
sidebar: sidebar 
permalink: known-limitations.html 
keywords: limitations, databases 
summary: このリリースの製品でサポートされていない、または正しく相互運用できないプラットフォーム、デバイス、または機能については、既知の制限事項が記載されています。これらの制限事項をよく確認してください。 
---
= NetApp Workload Factory for Databases の既知の制限事項
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
既知の制限事項では、 NetApp Workload Factory for Databases でサポートされていない、または正しく相互運用されないプラットフォーム、デバイス、または機能が特定されます。これらの制限事項をよく確認してください。



== インスタンス検出のサポート

Workload Factory は、Amazon Linux オペレーティング システムでのみ実行される PostgreSQL インスタンスと、Red Hat Enterprise Linux でのみ実行される Oracle インスタンスの検出をサポートしています。



== AMIイメージバージョンのサポート

SQLバージョンごとに、AMIイメージの最新バージョンまたはリビジョンが4つまで表示されます。最新の4つのバージョンより古いAMIイメージからのインストールは許可されていません。



== カスタムAMI

カスタムAMIを使用した展開では、インストールメディアがイメージに存在することが前提となります。これは、次の理由からFCIの設定に必要です。

* アンインストールして再設定し、FCIクラスタを形成するには
* スタンドアロン展開用にイメージ内の照合セット以外の照合を選択する場合


デプロイメントの一環として、Workload Factory は複数の Microsoft SQL Server インスタンスを含むカスタム AMI をインストールしません。展開の一部として、デフォルトの Microsoft SQL Server インスタンスのみが選択され、構成されます。



== 失敗した導入環境のロールバックと再試行

失敗したデプロイメントのロールバックと再試行は、Workload Factory ではサポートされていません。  AWS の CloudFormation コンソールから失敗したスタックをロールバックまたは再試行できます。



== Active DirectoryおよびDNSリソースのロールバック

AWSのCloudFormationコンソールからテストまたはデプロイに失敗した場合、次のDNSリソースはActive DirectoryおよびDNSから削除されません。

* SQL環境の各ノードの管理IPアドレスへの割り当て
* FCIの場合は、EC2インスタンスの予約済みセカンダリIPアドレスに対するWindowsクラスタ名
* FCIの両方のEC2インスタンスから2つの予約済みIPアドレスへのSQL FCI名


手動でクリーンアップするか、ドメインが古いエントリをパージするのを待つ必要があります。



== Always-On可用性グループ構成のサポート

Always On 可用性グループ構成の管理は、Workload Factory ではサポートされていません。



== カスタム暗号化キー

FSx for ONTAPのカスタム暗号化キーは、サービスの適用性に応じて表示されません。適切なキーを選択する必要があります。AWSで管理されるキーは、サービスへの適用性に基づいてフィルタリングされます。



== CloudFormationテンプレート

ダウンロードまたはコピーされたCodeboxで生成されたCloudFormationテンプレート（YAMLファイル）の保存期間は7日間に制限されています。



== サンドボックスのサポート

データベースサーバから作成できるサンドボックスクローンの最大数は90です。



== Microsoft SQL Serverの検出と管理

Microsoft SQL Server の検出は保存されません。  Workload Factory のデータベースにアクセスするたびに、Microsoft SQL Server の検出が再度実行され、そのリージョン内の SQL インストールが識別されます。



== コスト削減の詳細

[Inventory]タブでは、Microsoft SQLインスタンスごとに表示される推定コストは、SQLインスタンスをホストしているボリュームではなく、FSx for ONTAPファイルシステムレベルで計算されます。



== 複数のFSx for ONTAPファイルシステム

Workload Factoryでは、複数のFSx for ONTAPファイルシステムを使用するMicrosoft SQL Serverの構成の作成や保存はサポートされていません。FSx for ONTAPファイルシステム構成の導入は1つだけサポートされます。



== 最適化の制限事項



=== コンピューティングのサイズ適正化

特定のインスタンスタイプに変更すると、ネットワーク設定がリセットされ、最適化中にノード接続エラーが発生してジョブが失敗することがあります。DNS設定とiSCSIセッションを確認および更新するには、手動操作が必要になる場合があります。EC2サイズ変更の制限の詳細については、を参照してくださいlink:https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/resize-limitations.html["Amazon Elastic Compute Cloudのドキュメント"^]。



=== ONTAPとOSの設定の最適化

複数のSQL Serverインスタンスの一括最適化は、ONTAP構成およびOS構成ではサポートされていません。



=== 最適化のためのオペレーティングシステムパッチ評価

最適化の目的で行われるオペレーティング システム パッチ評価は、プライベート ネットワークでは機能しない可能性があります。評価は AWS Patch Manager に依存します。プライベートネットワーク内のWindows EC2インスタンスにパッチを適用する方法については、AWSクラウド運用ブログを参照してください。link:https://aws.amazon.com/blogs/mt/how-to-patch-windows-ec2-instances-in-private-subnets-using-aws-systems-manager/["AWS Systems Manager を使用してプライベートサブネット内の Windows EC2 インスタンスにパッチを適用する方法"^] 。



== オンプレミスでのコスト削減額の計算

オンプレミスのMicrosoft SQL Serverストレージのボリュームサイズのコスト削減率と削減率の計算は考慮されません。



== リージョン間レプリケーションの評価

* 最適化評価では、ターゲットのFSx for ONTAPファイルシステムが別のAWSアカウントにある場合、リージョン間レプリケーション（CRR）が使用されているかどうかを判断できません。
* Workload Factory は、ソース FSx for ONTAPファイル システムの CRR 構成のみを評価します。




== 節約を検討する際のデータベースホスト認証

権限が制限されている場合、認証が成功した後も節約の探索ページにデータが読み込まれないことがあります。



== NetAppバックアップおよびリカバリとの統合

保護のためにNetApp Backup and Recovery にホストを追加した後、データベースの検出が失敗することがあります。



== 地域サポート

次のAWSリージョンはサポートされません。

* 中国
* GovCloud（US）リージョン
* シークレットクラウド
* 極秘




== SUSE Linux Enterprise Server 12 への Oracle の登録

SUSE Linux Enterprise Server 12 に Oracle Database を登録する場合、Workload Factory は Python 依存関係をインストールしません。必要な Python バージョンを手動で設定する必要があります。  Workload Factory には最低バージョン 3.6 が必要ですが、バージョン 3.11 を推奨します。
