---
sidebar: sidebar 
permalink: known-limitations.html 
keywords: limitations, databases 
summary: このリリースの製品でサポートされていない、または正しく相互運用できないプラットフォーム、デバイス、または機能については、既知の制限事項が記載されています。これらの制限事項をよく確認してください。 
---
= 既知の制限事項
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
このリリースの製品でサポートされていない、または正しく相互運用できないプラットフォーム、デバイス、または機能については、既知の制限事項が記載されています。これらの制限事項をよく確認してください。



== AMIイメージバージョンのサポート

SQLバージョンごとに、AMIイメージの最新バージョンまたはリビジョンが4つまで表示されます。最新の4つのバージョンより古いAMIイメージからのインストールは許可されていません。



== カスタムAMI

カスタムAMIを使用した展開では、インストールメディアがイメージに存在することが前提となります。これは、次の理由からFCIの設定に必要です。

* アンインストールして再設定し、FCIクラスタを形成するには
* スタンドアロン展開用にイメージ内の照合セット以外の照合を選択する場合


導入の一環として、Workload Factoryでは、複数のMicrosoft SQL ServerインスタンスでカスタムAMIをインストールすることはありません。デフォルトのMicrosoft SQL Serverインスタンスのみが選択され、導入時に構成されます。



== 失敗した導入環境のロールバックと再試行

失敗した展開のロールバックと再試行は、Workload Factoryではサポートされていません。AWSのCloudFormationコンソールから、失敗したスタックをロールバックまたは再試行できます。



== Active DirectoryおよびDNSリソースのロールバック

AWSのCloudFormationコンソールからテストまたはデプロイに失敗した場合、次のDNSリソースはActive DirectoryおよびDNSから削除されません。

* SQL環境の各ノードの管理IPアドレスへの割り当て
* FCIの場合は、EC2インスタンスの予約済みセカンダリIPアドレスに対するWindowsクラスタ名
* FCIの両方のEC2インスタンスから2つの予約済みIPアドレスへのSQL FCI名


手動でクリーンアップするか、ドメインが古いエントリをパージするのを待つ必要があります。



== Always-On可用性グループ構成のサポート

常時稼働可用性グループ構成の管理は、Workload Factoryではサポートされていません。



== ユーザ管理のActive Directoryセキュリティグループ

Workload FactoryでMicrosoft SQL Serverを導入する際に「User-managed Active Directory」を選択した場合は、EC2インスタンスとディレクトリサービス間のトラフィックを導入用に許可するセキュリティグループを指定する必要があります。Workload Factoryは、AWS Managed Microsoft ADのように、ユーザー管理Active Directoryのセキュリティグループを自動的に添付しません。



== カスタム暗号化キー

FSx for ONTAPのカスタム暗号化キーは、サービスの適用性に応じて表示されません。適切なキーを選択する必要があります。AWSで管理されるキーは、サービスへの適用性に基づいてフィルタリングされます。



== CloudFormationテンプレート

ダウンロードまたはコピーされたCodeboxで生成されたCloudFormationテンプレート（YAMLファイル）の保存期間は7日間に制限されています。



== サンドボックスのサポート

データベースサーバから作成できるサンドボックスクローンの最大数は50です。



== Microsoft SQL Serverの検出と管理

Microsoft SQL Serverの検出は保存されません。Workload Factoryのデータベースにアクセスするたびに、Microsoft SQL Serverの検出が再度実行され、リージョン内のSQLインストールが特定されます。



== コスト削減の詳細

[Inventory]タブでは、Microsoft SQLインスタンスごとに表示される推定コストは、SQLインスタンスをホストしているボリュームではなく、FSx for ONTAPファイルシステムレベルで計算されます。



== 複数のFSx for ONTAPファイルシステム

Workload Factoryでは、複数のFSx for ONTAPファイルシステムを使用するMicrosoft SQL Serverの構成の作成や保存はサポートされていません。FSx for ONTAPファイルシステム構成の導入は1つだけサポートされます。
