---
sidebar: sidebar 
permalink: learn-databases.html 
keywords: Databases 
summary: NetApp Workload Factory for Databases は、最適化、自動シン クローニング、監視および解決機能に関するベスト プラクティスが組み込まれた、エンドツーエンドのデータベース導入および保守サービスです。 
---
= NetApp Workload Factory for Databases の詳細
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory for Databases は、最適化、自動シン クローニング、監視および解決機能に関するベスト プラクティスが組み込まれた、エンドツーエンドのデータベース導入および保守サービスです。



== NetApp Workload Factory for Databases とは何ですか?

NetApp Workload Factory for Databases は、Microsoft SQL Server データを検出、評価、計画、プロビジョニングし、業界のベストプラクティスに準拠しながらパフォーマンスとコストの期待に応えるように最適化されたAmazon FSx for NetApp ONTAP (FSx for ONTAP) デプロイメントに移動します。  NetApp Workload Factory for Databases は、ライフサイクル全体を通じて、FSx for ONTAP上のデータベースの継続的な最適化と管理を実現します。

ワークロードファクトリーの詳細については、link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["ワークロードファクトリーの概要"^] 。



== セルフマネージドデータベースにおけるワークロードファクトリーのメリット

Workload Factory は、自己管理型データベース向けに次のような有益なベスト プラクティスと自動化を提供します。



=== ベストプラクティス

* AWSクラウド、Microsoft WindowsおよびSQLサーバ、NetApp ONTAP for SQL ServerのEC2インスタンスへの導入に関する統合された知識。
* TCO（総所有コスト）最適化された導入。
* AWS、Microsoft、ONTAPのベストプラクティスに沿ったエンドツーエンドの導入自動化
* _クイック作成_ デプロイメント モードを使用すると、手動構成による潜在的な落とし穴を回避できます。




=== Workload Factory Codebox による自動化

Workload Factory は、_Codebox_ による組み込みの自動化を導入します。  Codebox は次のような自動化の利点を提供します。

* *コードスニペットの生成*：IAC（Infrastructure as Code）スニペットはリソース作成時に生成されるため、既存のオーケストレーションワークフローとシームレスに統合できます。
* *Infrastructure-as-code のコパイロット*: Codebox は、開発者と DevOps が Workload Factory でサポートされているあらゆる操作を実行するためのコードを生成するのに役立つ Infrastructure-as-code (IaC) コパイロットです。
* *コードビューアと自動化カタログ*:コードボックスは、自動化の迅速な分析のためのコードビューアと、将来の迅速な再利用のための自動化カタログを提供します。




=== データベース向けワークロードファクトリーの機能

Workload Factory for Databases は次の機能を提供します。

* *シンプルで迅速な導入*：仕様に関する質問に対する回答を選択し、Microsoft SQL Server on AWSのプロビジョニングおよび構成方法の調査に通常必要な時間を排除することで、プロビジョニングエクスペリエンスを簡素化および合理化します。
* *自動オーケストレーション*: Workload Factory コンソールの _Quick_ および _Advanced_ 作成デプロイメント モード、Chatbot、および Codebox 経由の AWS CloudFormation から利用できます。
* *組み込み機能*：NetApp、Microsoft、Amazonのベストプラクティスと、導入構成に組み込まれたAWSリソースの選択を活用します。
* *コストの見積もり*：Savings Calculatorを使用して、既存のMicrosoft SQL Server環境（Elastic Block StoreとFSx for Windowsファイルサーバを使用）のストレージ、コンピューティング、SQLライセンス、スナップショット、クローンの項目別コストを、FSx for ONTAPと比較して試算および詳細化し、削減可能なコストを評価します。
* *再利用可能な自動化テンプレート*: 複数の環境での将来の Microsoft SQL Server の展開のために、Workload Factory Codebox から CloudFormation テンプレートを作成、再利用、カスタマイズします。
* * AWSリソースの検出とプロビジョニング*：AWSアカウントから導入されたFSx for ONTAP、FSx for Windowsファイルサーバ、Elastic Block StoreでMicrosoft SQL Serverを自動的に検出します。データベースインベントリは、他のAWSストレージシステム内のサーバのコスト削減の余地を探るための出発点として機能し、FSx for ONTAPベースのサーバとインスタンスの管理ツールとして機能します。
* *サンドボックスの作成*：本番環境のデータに影響を与えることなく、テスト、統合、診断、トレーニングに使用できる、オンデマンドの分離されたデータベース環境を作成します。
* *データベースの作成*:データベースの照合、ファイル名、およびサイズを構成するために、_Quick_or_Advanced_createモードを使用して、既存のMicrosoft SQL Server用のユーザーデータベースを作成します。ストレージ構成も含まれます。
* *ジョブ監視*:データベースジョブの実行状況を監視および追跡し、障害が発生した場合の問題を診断およびトラブルシューティングします。
* *継続的な最適化*：Microsoft SQL Server環境をオフラインで継続的にスキャンし、優れた運用性の実現に役立つインサイト、機会、推奨事項の包括的なレポートを提供します。




== 自己管理型データベースでのAmazon FSx for ONTAPのメリット

* *耐久性、可用性、信頼性*：FSx for ONTAPは、単一および複数のアベイラビリティゾーンの導入をサポートする高可用性、アプリケーション対応のスナップショット、レプリケーションを使用したディザスタリカバリの向上、効率的なバックアップなど、FSx for ONTAPでホストされる自己管理データベースの耐久性と可用性を強化する複数の機能を提供します。
* *パフォーマンスと拡張性*：FSx for ONTAPは、高スループット、低レイテンシ、高速ネットワーク接続、複数のファイルシステムによる拡張性によってパフォーマンスを最適化し、ワークロードに必要なアグリゲートパフォーマンスを拡張します。
* *データの管理と効率化*：FSx for ONTAPは、スペース効率に優れたシンクローン、シンプロビジョニング、圧縮と重複排除、アクセス頻度の低いデータの容量プールへの階層化など、データの管理と効率化を強化する複数の機能を提供します。


link:https://docs.netapp.com/us-en/workload-fsx-ontap/learn-fsx-ontap.html["ワークロードファクトリー向け FSx for ONTAPの詳細"^] 。



=== ワークロードファクトリーの動作モード

3 つの異なる動作モード (_基本_、_読み取り専用_、_読み取り/書き込み_) により、Workload Factory の内外での展開に柔軟なオプションが提供されます。Workload Factory の外部で使用するためのコード スニペットを使用して、_基本_ モードでゼロ トラストの価値をすぐに得ることができます。_読み取り専用_ モードと _読み取り/書き込み_ モードで増分信頼を使用して増分値を取得します。

詳細はこちらlink:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html["ワークロードファクトリーの動作モード"^] 。



== NetApp Workload Factory を使用するためのツール

NetApp Workload Factory は次のツールで使用できます。

* *Workload Factory コンソール*: Workload Factory コンソールは、アプリケーションとプロジェクトの視覚的かつ全体的なビューを提供します。
* * NetAppコンソール*: NetAppコンソールはハイブリッド インターフェイス エクスペリエンスを提供するため、Workload Factory を他のNetAppデータ サービスと一緒に使用できます。
* *質問する*: Ask me AI アシスタントを使用すると、Workload Factory コンソールを離れることなく、質問したり、Workload Factory について詳しく知ることができます。Workload Factory のヘルプ メニューから「Ask me」にアクセスします。
* *CloudShell CLI*: Workload Factory には、単一のブラウザベースの CLI からアカウント全体の AWS およびNetApp環境を管理および操作するための CloudShell CLI が含まれています。Workload Factory コンソールの上部バーから CloudShell にアクセスします。
* *REST API*: Workload Factory REST API を使用して、FSx for ONTAPファイルシステムやその他の AWS リソースをデプロイおよび管理します。
* *CloudFormation*: AWS CloudFormation コードを使用して、Workload Factory コンソールで定義したアクションを実行し、AWS アカウントの CloudFormation スタックから AWS およびサードパーティのリソースをモデル化、プロビジョニング、管理します。
* *Terraform NetApp Workload Factory プロバイダー*: Terraform を使用して、Workload Factory コンソールで生成されたインフラストラクチャ ワークフローを構築および管理します。




== サポートされる構成

Workload Factory は、AWS、 NetApp ONTAP、Microsoft SQL Server、Oracle、PostgreSQL のベストプラクティスに従って、次のデータベース エンジン、バージョン、オペレーティング システム、およびデプロイメント モデルをサポートしています。

[cols="1,1,1,1"]
|===
| エンジン | version | オペレーティング システム | 展開モデル 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2016 | FCI、単一インスタンス 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2016 | FCI、単一インスタンス 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2016 | FCI、単一インスタンス 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2019 | FCI、単一インスタンス 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2019 | FCI、単一インスタンス 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2019 | FCI、単一インスタンス 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2022 | FCI、単一インスタンス 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2022 | FCI、単一インスタンス 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2022 | FCI、単一インスタンス 


| Microsoft SQL Server | SQL Server 2017 | any | FCI、単一インスタンス 


| Microsoft SQL Server | SQL Server 2016、2017、2019、2022 | any | FCI、単一インスタンス 


| Oracle | 19世紀 | RHEL、SuSe Linux | スタンドアロン（シングル/マルチテナント） 


| Oracle | 21c | RHEL、SuSe Linux | スタンドアロン（シングル/マルチテナント） 


| Oracle | 19世紀 | RHEL、SuSe Linux | スタンドアロン（シングル/マルチテナント） 


| Oracle | 21c | RHEL、SuSe Linux | スタンドアロン（シングル/マルチテナント） 


| Oracle | 19世紀 | RHEL、SuSe Linux | ASM を使用したスタンドアロン (シングル/マルチテナント) 


| Oracle | 21c | RHEL、SuSe Linux | ASM を使用したスタンドアロン (シングル/マルチテナント) 


| PostgreSQL | PostgreSQL 15 | Amazon Linux 2023 AMI | HA、スタンドアロンインスタンス 


| PostgreSQL | PostgreSQL 16 | Amazon Linux 2023 AMI | HA、スタンドアロンインスタンス 
|===


== AWS統合サービス

データベースには、次のAWS統合サービスが含まれています。

* クラウド形成
* 簡易通知サービス
* CloudWatch
* System Manager
* シークレットマネージャー




== 地域

データベースは、FSx for ONTAPがサポートされるすべての商用リージョンでサポートされます。 https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["サポート対象の Amazon リージョンを表示します。"^]

次のAWSリージョンはサポートされません。

* 中国
* GovCloud（US）リージョン
* シークレットクラウド
* トップシークレットクラウド




== サポートを受ける

Amazon FSx for NetApp ONTAP は、AWSファーストパーティの解決策 です。FSx for ONTAPファイルシステム、インフラ、または本サービスを使用する解決策に関する質問やテクニカルサポートの問題については、AWS管理コンソールのサポートセンターを使用してAWSに対するサポートケースをオープンしてください。「 FSX for ONTAP 」サービスと該当するカテゴリを選択します。AWS サポートケースの作成に必要な残りの情報を指定します。

Workload FactoryまたはWorkload Factoryアプリケーションとサービスに関する一般的な質問については、以下を参照してください。link:get-help.html["NetApp Workload Factory for Databases のヘルプを入手する"] 。
