---
sidebar: sidebar 
permalink: learn-databases.html 
keywords: Databases 
summary: NetApp Workload Factory for Databases は、最適化、自動シン クローニング、監視および解決機能に関するベスト プラクティスが組み込まれた、エンドツーエンドのデータベース導入および保守サービスです。 
---
= NetApp Workload Factory for Databases の詳細
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory for Databases は、最適化、自動シン クローニング、監視および解決機能に関するベスト プラクティスが組み込まれた、エンドツーエンドのデータベース導入および保守サービスです。



[[what-is-netapp-workload-factory-for-databases]]
== NetApp Workload Factory for Databases とは何ですか?

NetApp Workload Factory for Databasesは、Microsoft SQL Server、PostgreSQL、およびOracleデータを検出、評価、計画、プロビジョニングし、業界のベストプラクティスを遵守しながら、パフォーマンスとコストの期待に応えるように最適化されたAmazon FSx for NetApp ONTAP（FSx for ONTAP）環境に移行します。NetApp Workload Factory for Databasesは、FSx for ONTAP上のデータベースを継続的に最適化および管理します。

ワークロードファクトリーの詳細については、link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["ワークロードファクトリーの概要"^] 。



[[workload-factory-benefits-for-self-managed-databases]]
== セルフマネージドデータベースにおけるワークロードファクトリーのメリット

Workload Factoryは、自己管理型データベース向けのベストプラクティスと自動化機能を提供します。



[[best-practices]]
=== ベストプラクティス

* AWSクラウド、Microsoft WindowsおよびSQLサーバ、NetApp ONTAP for SQL ServerのEC2インスタンスへの導入に関する統合された知識。
* TCO（総所有コスト）最適化された導入。
* AWS、Microsoft、ONTAPのベストプラクティスに沿ったエンドツーエンドの導入自動化
* _クイック作成_ デプロイメント モードを使用すると、手動構成による潜在的な落とし穴を回避できます。




[[automation-with-workload-factory-codebox]]
=== Workload Factory Codebox による自動化

Workload Factory は、_Codebox_ による組み込みの自動化を導入します。  Codebox は次のような自動化の利点を提供します。

* *コードスニペットの生成*：Workload Factoryは、リソース作成時にInfrastructure-as-Code（IaC）スニペットを生成し、既存のオーケストレーションワークフローとのシームレスな統合を可能にします。
* *Infrastructure-as-code のコパイロット*: Codebox は、開発者と DevOps が Workload Factory でサポートされているあらゆる操作を実行するためのコードを生成するのに役立つ Infrastructure-as-code (IaC) コパイロットです。
* *コードビューアと自動化カタログ*:コードボックスは、自動化の迅速な分析のためのコードビューアと、将来の迅速な再利用のための自動化カタログを提供します。




[[workload-factory-for-databases-features]]
=== データベース向けワークロードファクトリーの機能

Workload Factory for Databases は次の機能を提供します。

* *コスト見積もり*：Elastic Block Store、FSx for Windows File Server、オンプレミスと比較して、FSx for ONTAPを使用した既存のMicrosoft SQL ServerおよびOracleデプロイメントのストレージ、コンピューティング、SQLライセンス、スナップショット、クローンの項目別コストを見積もり、詳細化する節約計算ツールを使用して、潜在的なコスト削減を評価します。
* *シンプルで高速な導入*：組み込みのNetApp、Microsoft、Amazon のベストプラクティスにより、ホスト、データベース、サンドボックスのプロビジョニングを簡素化および合理化し、AWS 上の Microsoft SQL Server および PostgreSQL インスタンスの手動設定の複雑さを排除します。
+
** Workload Factory コンソールから_Quick_または_Advanced_作成モードを使用してデプロイするか、Codebox を通じて AWS CloudFormation テンプレートを作成、再利用、カスタマイズして、複数の環境にわたる将来のデプロイメントに活用します。
** 本番データに影響を与えることなく、テスト、統合、診断、トレーニングに使用できる、ストレージ構成とサンドボックスクローンを備えたオンデマンドの隔離されたデータベースを作成します。


* *Well-architected assessment機能*:Microsoft SQL ServerおよびOracleの環境を継続的にスキャンし、AWSのベストプラクティスに基づいて運用上の卓越性、セキュリティ、信頼性、パフォーマンス効率、コスト最適化の実現に役立つ洞察、機会、推奨事項を網羅した包括的なレポートを提供します。
* *エラー分析*：AIアナライザーを使用してログエラーを分析およびトラブルシューティングし、詳細なエラーメッセージ、トラブルシューティング手順、および問題を解決するための推奨事項を取得します。
* *集中管理*：Microsoft SQL Server、Oracle、PostgreSQL の各リソースを FSx for ONTAP 上で一元管理できます。Workload Factory では、接続されているインフラ、AWS アカウント、クレデンシャル、接続されている FSx for ONTAP ファイルシステム、NFS ボリュームや iSCSI LUN を含むストレージ使用状況、保護ステータス、パフォーマンス、Well-Architected ステータス、エラー分析を表示できます。




[[benefits-of-amazon-fsx-for-ontap-for-self-managed-databases]]
== 自己管理型データベースでのAmazon FSx for ONTAPのメリット

* *耐久性、可用性、信頼性*：FSx for ONTAPは、単一および複数のアベイラビリティゾーンの導入をサポートする高可用性、アプリケーション対応のスナップショット、レプリケーションを使用したディザスタリカバリの向上、効率的なバックアップなど、FSx for ONTAPでホストされる自己管理データベースの耐久性と可用性を強化する複数の機能を提供します。
* *パフォーマンスと拡張性*：FSx for ONTAPは、高スループット、低レイテンシ、高速ネットワーク接続、複数のファイルシステムによる拡張性によってパフォーマンスを最適化し、ワークロードに必要なアグリゲートパフォーマンスを拡張します。
* *データの管理と効率化*：FSx for ONTAPは、スペース効率に優れたシンクローン、シンプロビジョニング、圧縮と重複排除、アクセス頻度の低いデータの容量プールへの階層化など、データの管理と効率化を強化する複数の機能を提供します。


link:https://docs.netapp.com/us-en/workload-fsx-ontap/learn-fsx-ontap.html["ワークロードファクトリー向け FSx for ONTAPの詳細"^] 。



[[tools-to-use-netapp-workload-factory]]
== NetApp Workload Factory を使用するためのツール

NetApp Workload Factory は次のツールで使用できます。

* *Workload Factory コンソール*: Workload Factory コンソールは、アプリケーションとプロジェクトの視覚的かつ全体的なビューを提供します。
* * NetAppコンソール*: NetAppコンソールはハイブリッド インターフェイス エクスペリエンスを提供するため、Workload Factory を他のNetAppデータ サービスと一緒に使用できます。
* *質問する*: Ask me AI アシスタントを使用すると、Workload Factory コンソールを離れることなく、質問したり、Workload Factory について詳しく知ることができます。Workload Factory のヘルプ メニューから「Ask me」にアクセスします。
* *CloudShell CLI*: Workload Factory には、単一のブラウザベースの CLI からアカウント全体の AWS およびNetApp環境を管理および操作するための CloudShell CLI が含まれています。Workload Factory コンソールの上部バーから CloudShell にアクセスします。
* *REST API*: Workload Factory REST API を使用して、FSx for ONTAPファイルシステムやその他の AWS リソースをデプロイおよび管理します。
* *CloudFormation*: AWS CloudFormation コードを使用して、Workload Factory コンソールで定義したアクションを実行し、AWS アカウントの CloudFormation スタックから AWS およびサードパーティのリソースをモデル化、プロビジョニング、管理します。
* *Terraform NetApp Workload Factory プロバイダー*: Terraform を使用して、Workload Factory コンソールで生成されたインフラストラクチャ ワークフローを構築および管理します。




[[supported-configurations]]
== サポートされる構成

Workload Factoryは、AWS、NetApp ONTAP、Microsoft SQL Server、Oracle、およびPostgreSQLのベストプラクティスに従い、以下のデータベースエンジン、バージョン、オペレーティングシステム、および導入モデルで使用できます。

[cols="1,1,1,1"]
|===
| エンジン | version | オペレーティング システム | 展開モデル 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2016 | FCI、Standalone 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2016 | FCI、Standalone 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2016 | FCI、Standalone 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2019 | FCI、Standalone 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2019 | FCI、Standalone 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2019 | FCI、Standalone 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2022 | FCI、Standalone 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2022 | FCI、Standalone 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2022 | FCI、Standalone 


| Microsoft SQL Server | SQL Server 2017 | any | FCI、Standalone 


| Microsoft SQL Server | SQL Server 2016、2017、2019、2022 | any | FCI、Standalone 


| Microsoft SQL Server | SQL Server 2016、2017、2019、2022 | any | Always On 可用性グループ 


| Oracle | 19世紀 | RHEL、SuSe Linux | スタンドアロン（シングル/マルチテナント） 


| Oracle | 21c | RHEL、SuSe Linux | スタンドアロン（シングル/マルチテナント） 


| Oracle | 19世紀 | RHEL、SuSe Linux | スタンドアロン（シングル/マルチテナント） 


| Oracle | 21c | RHEL、SuSe Linux | スタンドアロン（シングル/マルチテナント） 


| Oracle | 19世紀 | RHEL、SuSe Linux | ASM を使用したスタンドアロン (シングル/マルチテナント) 


| Oracle | 21c | RHEL、SuSe Linux | ASM を使用したスタンドアロン (シングル/マルチテナント) 


| Oracle | 19c、21c | RHEL、SuSe Linux | Data Guard 


| PostgreSQL | PostgreSQL 15 | Amazon Linux 2023 AMI | HA、スタンドアロンインスタンス 


| PostgreSQL | PostgreSQL 16 | Amazon Linux 2023 AMI | HA、スタンドアロンインスタンス 
|===


[[integrated-aws-services]]
== AWS統合サービス

データベースには、以下の統合されたAWSサービスが含まれています：

* クラウド形成
* 簡易通知サービス
* CloudWatch
* System Manager
* シークレットマネージャー




[[regions]]
== 地域

データベースは、FSx for ONTAPがサポートされるすべての商用リージョンでサポートされます。 https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["サポート対象の Amazon リージョンを表示します。"^]

次のAWSリージョンはサポートされません。

* 中国
* シークレットクラウド
* トップシークレットクラウド




[[getting-help]]
== サポートを受ける

Amazon FSx for NetApp ONTAP は、AWSファーストパーティの解決策 です。FSx for ONTAPファイルシステム、インフラ、または本サービスを使用する解決策に関する質問やテクニカルサポートの問題については、AWS管理コンソールのサポートセンターを使用してAWSに対するサポートケースをオープンしてください。「 FSX for ONTAP 」サービスと該当するカテゴリを選択します。AWS サポートケースの作成に必要な残りの情報を指定します。

Workload FactoryまたはWorkload Factoryアプリケーションとサービスに関する一般的な質問については、以下を参照してください。link:get-help.html["NetApp Workload Factory for Databases のヘルプを入手する"] 。
