---
sidebar: sidebar 
permalink: monitor-databases.html 
keywords: monitor databases, monitor jobs, track database jobs 
summary: NetApp Workload Factory for Databases 内でデータベース ジョブを追跡し、データベースを監視します。 
---
= Workload Factory for Databases でデータベース ジョブを監視する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory for Databases 内でデータベース ジョブを追跡し、データベースを監視して、データベース操作の可視性と制御を向上させます。



== タスクの内容

データベースにはジョブ監視機能があり、ジョブの進捗状況を追跡したり、障害が発生した場合の診断とトラブルシューティングを行うことができます。タイプとステータスでジョブをフィルタリングしたり、検索機能を使用してジョブを検索したり、ジョブテーブルをダウンロードしたりできます。

ジョブ監視では、ジョブに応じて最大3つのレベルの監視がサポートされます。たとえば、新しいデータベースおよびサンドボックスクローンの作成では、ジョブ監視によって親ジョブとサブジョブが追跡されます。

.ジョブ監視レベル
* レベル1（親ジョブ）：ホスト導入ジョブを追跡します。
* レベル2（サブジョブ）：ホスト展開の親ジョブに関連するサブジョブを追跡します。
* レベル3（タスク）：各リソースに対して実行された一連のアクションを一覧表示します。


.ジョブステータス
ジョブ監視機能では、_ in progress_、_ completed_、_ completed with issues_、_ failed_jobs daily、weekly、bi-weekly、およびmonthlyが追跡されます。

.ジョブイベントの保持
ジョブ監視イベントは、ユーザインターフェイスに30日間保持されます。



== ジョブの監視

ジョブを監視してデータベース操作の進行状況を追跡し、障害が発生した場合に診断およびトラブルシューティングを行います。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. [データベース] メニューから、[ジョブ監視] を選択します。
. ジョブ監視では、フィルターまたは検索を使用してジョブの結果を絞り込みます。求人レポートをダウンロードすることもできます。
. オプションで、ジョブのアクションメニューを選択し、「*CloudFormation に移動*」をクリックして、AWS CloudFormation コンソールでジョブのログを表示します。

