---
sidebar: sidebar 
permalink: monitor-databases.html 
keywords: monitor databases, monitor jobs, track database jobs 
summary: データベースのジョブを追跡し、BlueXP  ワークロードファクトリ内のデータベースを監視します。 
---
= BlueXP  Workload Factoryでのデータベースの監視
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
データベースのジョブを追跡し、BlueXP  ワークロードファクトリ内のデータベースを監視します。

.タスクの内容
データベースにはジョブ監視機能があり、ジョブの進捗状況を追跡したり、障害が発生した場合の診断とトラブルシューティングを行うことができます。また、タイプとステータス、検索機能、およびジョブテーブルをダウンロードするためのオプションによってフィルタリングされ、データベースジョブのナビゲーションとレポート作成に役立ちます。

ジョブ監視では、ジョブに応じて最大3つのレベルの監視がサポートされます。たとえば、新しいデータベースおよびサンドボックスクローンの作成では、ジョブ監視によって親ジョブとサブジョブが追跡されます。

ジョブ監視レベル::
+
--
* レベル1（親ジョブ）：ホスト導入ジョブを追跡します。
* レベル2（サブジョブ）：ホスト展開の親ジョブに関連するサブジョブを追跡します。
* レベル3（タスク）：各リソースに対して実行された一連のアクションを一覧表示します。


--
ジョブステータス:: ジョブ監視機能は、_進行中_、_完了_、_失敗_のジョブを毎日、毎週、隔週、および毎月追跡します。
ジョブイベントの保持:: ジョブ監視イベントは、ユーザインターフェイスに30日間保持されます。




== ジョブの監視

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. [データベース]で、*[ジョブの監視]*タブを選択します。
. [ジョブ監視]タブで、フィルタを使用するか検索してジョブの結果を絞り込みます。ジョブレポートをダウンロードすることもできます。
. ジョブの3つのドットメニューをクリックし、* Go to CloudFormation *をクリックして、AWS CloudFormationコンソールにジョブログを表示します。

