---
sidebar: sidebar 
permalink: optimize-configurations.html 
keywords: optimize, configuration, storage, compute, application, resiliency assessment, scan, optimization, Microsoft SQL Server, host, instance, FSx for ONTAP 
summary: Workload Factory for Databases は、Microsoft SQL Server の構成をスキャンし、運用効率の向上に役立つ洞察と推奨事項を提供します。 
---
= ワークロードファクトリーで適切に設計されたデータベース構成を実装する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
構成分析の洞察と推奨事項を活用し、ワークロードファクトリーを活用してデータベース構成のベストプラクティスを実装します。信頼性、セキュリティ、効率性、パフォーマンス、コストが最適化されていない構成の問題を簡単に特定し、アーキテクチャを改善するための対策を講じることができます。

.タスクの内容
ワークロードファクトリーはデータベース構成を毎日分析します。毎日の分析では、構成の問題を自動的に修正するためのオプションを含む洞察と推奨事項が提供され、構成がベストプラクティスに準拠するようにします。

ワークロード ファクトリ コンソール内のデータベース インベントリから、構成の問題に関する推奨事項を確認し、それらの問題を修正するオプションがあります。

分析対象:: ワークロード ファクトリーは、Microsoft SQL Server インスタンスの次の構成の well-architected ステータスを分析します。
+
--
* ストレージのサイジング：ストレージ階層、ファイルシステムのヘッドルーム、ログドライブのサイズ、tempdbドライブのサイズを含む
* ストレージレイアウト：ユーザデータファイルの配置、ログファイルの配置、tempdbの配置を含む
* ストレージ構成: 容量管理、シンプロビジョニング、階層化ポリシー、スナップショット、Microsoft マルチパス I/O (MPIO) ステータス、および MPIO タイムアウト設定が含まれます。
* コンピューティング：サイズ適正化、オペレーティングシステムのパッチ、受信側スケーリング（RSS）やTCPオフロードなどのネットワークアダプタ設定を含む
* アプリケーション：Microsoft SQL Serverライセンス、Microsoft SQL Serverパッチ、およびMAXDOP設定を含む
* 耐障害性：ローカルSnapshot、FSx for ONTAPバックアップ、リージョン間レプリケーション（CRR）など
* クローン: ワークロード ファクトリー内または外で作成され、60 日以上経過したクローン (サンドボックス) を更新および削除するオプションが含まれます。


--


.開始する前に
* あなたは持っている必要がありますlink:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWS アカウントの認証情報と読み取り/書き込み権限"^]データベース構成を分析します。
* Microsoft SQL Server インスタンスのストレージを評価するには、インスタンスがワークロード ファクトリに登録され、ストレージ タイプが FSx for ONTAP である必要があります。 link:register-instance.html["ホスト インスタンスを登録する方法を学びます。"]
* 設定または構成の修正を選択する前に、各推奨事項をよく確認してください。RSSおよびMAXDOPの設定については、本番環境を変更する前に、推奨設定をテストしてパフォーマンスの向上を確認することをお勧めします。



NOTE: 修正プロセスによって、インスタンスのダウンタイムやサービスの中断が発生する可能性があります。構成を修正することを選択する前に、推奨事項を慎重に確認してください。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. [インベントリ（Inventory）]*タブで、*[インスタンス（Instances）]*タブを選択します。
. インスタンスの構成の問題を表示するには、[*問題を修正*] を選択します。
. ホスト インスタンスの Well-architected ステータス ページで、分析の結果を確認します。
+
構成の問題は、カテゴリ、サブカテゴリ、ステータス、重大度、タグでフィルタリングできます。

+
*PDF エクスポート* を選択して、調査結果のレポートをダウンロードすることもできます。

. ドロップダウン矢印を選択すると、構成の推奨事項が表示されます。推奨事項には、ベスト プラクティス、最適化されていない構成の潜在的な落とし穴、重要な考慮事項が含まれます。推奨事項をよく確認してください。
. オプションが利用可能な場合は、構成の問題を*表示して修正*することを選択します。
+
*すべて選択*がデフォルトですが、修正する特定のリソースを選択することもできます。

+
.. クローン クリーンアップ以外のすべての構成については、推奨事項の詳細を確認して、問題を修正した場合に何が起こるかを確認してください。一部の修復操作では、インスタンスのダウンタイムやサービスの中断が発生する可能性があります。
.. クローンクリーンアップでは、更新または削除するクローンデータベース（サンドボックス）を選択します。
+
*** クローンを更新すると、クローンがソースデータベースと同期されます。更新は、ワークロード工場で作成されたクローンに対してのみ使用できます。
*** クローンを削除すると、クローンが完全に削除され、ストレージスペースが解放されてコストが削減されます。ワークロードファクトリ内外で作成されたクローンを削除できます。




. 構成の問題を修正するには、*[続行]*を選択します。


.結果
ワークロード ファクトリーが問題の修正を開始します。[ジョブ監視]*タブを選択して処理のステータスを表示します。
