---
sidebar: sidebar 
permalink: optimize-configurations.html 
keywords: optimize, configuration, storage, compute, application, resiliency assessment, scan, optimization, Microsoft SQL Server, host, instance, FSx for ONTAP 
summary: Workload Factory for Databases は、Microsoft SQL Server の構成をスキャンし、運用効率の向上に役立つ洞察と推奨事項を提供します。 
---
= ワークロードファクトリーで適切に設計されたデータベース構成を実装する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
構成分析の洞察と推奨事項を使用して、ワークロード ファクトリを活用し、Microsoft SQL Server および Oracle を使用したデータベース構成のベスト プラクティスを実装します。  Well-Architected ステータスを簡単に確認し、データベース構成の問題を把握し、信頼性、セキュリティ、効率、パフォーマンス、コストが最適化されていない構成を改善するための措置を講じることができます。

不要なアラートや不正確な最適化結果を回避するために、環境に当てはまらない特定の構成の分析を無視することもできます。

link:optimize-overview.html["ワークロード ファクトリーの構成分析と Well-Architected ステータスについて学習します。"]



== タスクの内容

ワークロードファクトリーはデータベース構成を毎日分析します。毎日の分析では、適切に設計されたステータス、洞察、推奨事項が提供され、構成がベスト プラクティスを満たすように構成の問題を自動的に修正するオプションも提供されます。

ワークロード ファクトリ コンソール内のデータベース インベントリから、構成の問題に関する推奨事項を確認し、それらの問題を修正するオプションがあります。

.分析対象
ワークロード ファクトリーは、次の構成の well-architected ステータスを分析します。

Microsoft SQL Server インスタンスの場合:

* ストレージのサイジング：ストレージ階層、ファイルシステムのヘッドルーム、ログドライブのサイズ、tempdbドライブのサイズを含む
* ストレージレイアウト：ユーザデータファイルの配置、ログファイルの配置、tempdbの配置を含む
* ストレージ構成: 容量管理、シンプロビジョニング、階層化ポリシー、スナップショット、Microsoft マルチパス I/O (MPIO) ステータス、および MPIO タイムアウト設定が含まれます。
* コンピューティング: 適切なサイズ設定、オペレーティング システムのパッチ、受信側スケーリング (RSS)、TCP オフロード、MTU アライメントなどのネットワーク アダプタ設定が含まれます。
* アプリケーション：Microsoft SQL Serverライセンス、Microsoft SQL Serverパッチ、およびMAXDOP設定を含む
* 回復力: ローカル スナップショット、FSx for ONTAPバックアップ、クロスリージョン レプリケーション (CRR)、Microsoft SQL High Availability が含まれます。
* クローン: ワークロード ファクトリー内または外で作成され、60 日以上経過したクローン (サンドボックス) を更新および削除するオプションが含まれます。


Oracle データベースの場合:

* ストレージ構成: 容量管理、シンプロビジョニング、階層化ポリシー、スナップショット、ストレージ効率などが含まれます




== 開始する前に

* あなたは持っている必要がありますlink:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWS アカウントの認証情報と読み取り/書き込み権限"^]データベース構成を分析します。
* Microsoft SQL Server インスタンスまたは Oracle データベースのストレージを評価するには、リソースをワークロード ファクトリに登録し、ストレージ タイプを FSx for ONTAPにする必要があります。link:register-instance.html["リソースを登録する方法を学びます。"]
* 設定または構成の修正を選択する前に、各推奨事項をよく確認してください。RSSおよびMAXDOPの設定については、本番環境を変更する前に、推奨設定をテストしてパフォーマンスの向上を確認することをお勧めします。



NOTE: 修正プロセスによって、インスタンスのダウンタイムやサービスの中断が発生する可能性があります。構成を修正することを選択する前に、推奨事項を慎重に確認してください。



== 構成の問題を修正する

FSx for ONTAPストレージ上で実行されている SQL Server または Oracle 環境の構成の問題を修正します。


NOTE: 修復プロセスにより、インスタンスのダウンタイムやサービスの中断が発生する可能性があります。構成の問題を修正することを選択する前に、推奨事項を慎重に確認してください。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. [インベントリ（Inventory）]*タブで、*[インスタンス（Instances）]*タブを選択します。
. インスタンスの構成の問題を表示するには、[*問題を修正*] を選択します。
. インスタンスの Well-architected ステータス ページで、分析の結果を確認します。
+
構成の問題は、カテゴリ、サブカテゴリ、ステータス、重大度、タグでフィルタリングできます。

+
*PDF エクスポート* を選択して、調査結果のレポートをダウンロードすることもできます。

. ドロップダウン矢印を選択すると、構成の推奨事項が表示されます。推奨事項には、ベスト プラクティス、最適化されていない構成の潜在的な落とし穴、重要な考慮事項が含まれます。推奨事項をよく確認してください。
. オプションが利用可能な場合は、構成の問題を*表示して修正*することを選択します。
+
*すべて選択*がデフォルトですが、修正する特定のリソースを選択することもできます。

+
.. クローン クリーンアップ以外のすべての構成については、推奨事項の詳細を確認して、問題を修正した場合に何が起こるかを確認してください。一部の修復操作では、インスタンスのダウンタイムやサービスの中断が発生する可能性があります。
.. クローンクリーンアップでは、更新または削除するクローンデータベース（サンドボックス）を選択します。
+
*** クローンを更新すると、クローンがソースデータベースと同期されます。更新は、ワークロード工場で作成されたクローンに対してのみ使用できます。
*** クローンを削除すると、クローンが完全に削除され、ストレージスペースが解放されてコストが削減されます。ワークロードファクトリ内外で作成されたクローンを削除できます。




. 構成の問題を修正するには、*[続行]*を選択します。


.結果
ワークロード ファクトリーが問題の修正を開始します。[ジョブ監視]*タブを選択して処理のステータスを表示します。



== データベース設定の分析を延期または却下する

不要なアラートや不正確な最適化結果を回避するために、データベース環境に適用されない特定のデータベース構成の分析を延期または却下します。延期または却下された構成分析は、いつでも再アクティブ化できます。

データベース構成のアプリケーション要件は異なります。Workload Factoryには、特定のデータベース構成の分析を省略する2つのオプションがあります。これにより、関連する問題のみを監視し、関連する構成の健全性を正確に把握できます。特定の構成分析が延期または却下された場合、その構成は合計最適化スコアに含まれません。

構成分析は、構成レベル、SQL Server インスタンス、または Oracle データベース レベルで延期、破棄、再アクティブ化できます。

* * 30日間延期*：解析を延期すると、解析が30日間停止します。30日後、分析は自動的に再開されます。
* *却下*：解析を却下すると、解析が無期限に延期されます。必要に応じて解析を再開できます。


次の手順では、構成レベルで分析を延期、却下、または再アクティブ化する方法について説明します。特定の SQL Server インスタンスまたは Oracle データベースに対して次のタスクを完了するには、[ダッシュボード] タブから開始します。

[role="tabbed-block"]
====
.延期
--
設定分析を30日間停止するように延期します。30日後、分析は自動的に再開されます。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. [Inventory]*タブで、[Postpone]の設定まで下にスクロールし、3ドットのメニューを選択して[* Postpone for 30 days]*を選択します。
. 「 * Continue * 」を選択します。


.結果
設定の分析が30日間停止します。

--
.却下
--
構成分析を無期限に停止するには、[却下]をクリックします。必要に応じて解析を再開できます。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. [Inventory]*タブで、閉じる構成まで下にスクロールし、3ドットのメニューを選択して、*[Dismiss]*を選択します。
. 「 * Continue * 」を選択します。


.結果
構成分析が停止します。

--
.再アクティブ化
--
延期または却下された構成分析をいつでも再アクティブ化できます。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. [Inventory]*タブで、再アクティブ化する構成まで下にスクロールし、3ドットのメニューを選択して[* Reactivate]*を選択します。
. 「 * Continue * 」を選択します。


.結果
構成分析が再アクティブ化され、毎日実行されます。

--
====