---
sidebar: sidebar 
permalink: optimize-configurations.html 
keywords: optimize, configuration, storage, compute, application, resiliency assessment, scan, optimization, Microsoft SQL Server, host, instance, FSx for ONTAP 
summary: BlueXP  Workload Factory for Databasesは、Microsoft SQL Serverの構成をスキャンし、優れた運用性の実現に役立つ分析情報と推奨事項を提供します。 
---
= Microsoft SQL Server環境向けに構成を最適化
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  Workload Factory for Databasesは、Amazon FSx for NetApp ONTAPで実行されるMicrosoft SQL Server導入構成を継続的にスキャンして評価します。この機能は、分析情報と推奨事項を提供するとともに、最適化されていない構成を自動的に最適化して、データベースワークロードの優れた運用性を実現するオプションも提供します。

.タスクの内容
この評価は、ワークロード工場で管理されているFSx for ONTAPストレージを使用して、Microsoft SQL Serverインスタンスについて毎日1回自動的かつ継続的に実行されます。評価レポートは、導入後またはインスタンスの管理後に毎日スケジュールされたジョブが実行された場合にのみ、最適化ダッシュボードで使用できます。

ワークロードファクトリからは、FSx for ONTAPストレージのベストプラクティスに基づいて構成を最適化するための詳細な推奨事項が提供されます。

スキャン対象:: Workload Factoryは、Microsoft SQL Serverインスタンスについて次の構成の最適化ステータスを評価します。
+
--
* ストレージのサイジング：ストレージ階層、ファイルシステムのヘッドルーム、ログドライブのサイズ、tempdbドライブのサイズを含む
* ストレージレイアウト：ユーザデータファイルの配置、ログファイルの配置、tempdbの配置を含む
* ストレージ構成：容量管理、シンプロビジョニング、階層化ポリシー、Snapshot、マルチパスI/Oステータス、ポリシー、セッションなど
* コンピューティング：サイズ適正化とオペレーティングシステムのパッチを含む
* アプリケーション：Microsoft SQL Serverライセンスを含む


--


.開始する前に
* 読み取りまたは自動化の権限を持つクレデンシャルが必要です。
* Microsoft SQL Serverインスタンスのストレージを評価するには、インスタンスがワークロード工場で管理されていて、ストレージタイプがFSx for ONTAPである必要があります。
* 設定または構成の最適化を選択する前に、各推奨事項をよく確認してください。


.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. [Inventory]*タブで、ドロップダウン矢印を選択してホストの行を展開し、管理対象インスタンスを表示します。
+
ホストが展開され、ホストインスタンスが表示されます。

. インスタンスの3ドットメニューを選択し、*最適化*を選択します。
. SQL Serverインスタンスの[Optimize instance]ページで、評価結果を確認します。
+
カテゴリ、サブカテゴリ、ステータス、重大度、およびタグでフィルタリングできます。

+
[Export PDF]を選択して、評価結果のレポートをダウンロードすることもできます。

. ドロップダウン矢印を選択すると、構成の推奨事項が表示されます。推奨事項をよく確認してください。
+
推奨事項には、最適化されていない構成のベストプラクティスと潜在的な落とし穴が記載されています。

. [Optimize * unoptimized configurations]を選択します。
. 最適化ダイアログに表示される最適化の概要とアクション項目を確認して、最適化を選択した場合の動作を確認します。最適化処理によっては、インスタンスのダウンタイムやサービスの中断が発生する場合があります。
. 構成を最適化するには、* Continue *を選択します。


.結果
最適化プロセスが開始されます。[ジョブ監視]*タブを選択して処理のステータスを表示します。
