---
sidebar: sidebar 
permalink: optimize-overview.html 
keywords: database configuration issues, issues, analyze, scan, optimize, improve, database configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations, storage, compute, application, resiliency, scan, optimization, SQL Server, host, instance 
summary: Workload Factory for Databases は、Microsoft SQL Server および Oracle の構成を定期的に分析して、問題があるかどうかを判断します。 
---
= Workload Factory におけるデータベース環境の構成分析
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory for Databases は、データベース構成を定期的に分析して、 Amazon FSx for NetApp ONTAPストレージ上の Microsoft SQL Server および Oracle のデプロイメントに問題があるかどうかを判断します。問題が見つかった場合、Workload Factory は問題の内容を示し、データベース構成で最高のパフォーマンス、コスト効率、ベスト プラクティスへの準拠を実現するために何を変更する必要があるかを説明します。

主な機能は次のとおりです。

* 日常的な構成分析
* ベストプラクティスの自動検証
* サイズの適正化に関する推奨事項
* プロアクティブなオブザーバビリティ
* インサイトからアクションへ
* AWS Well-Architected Framework Advisor




== 構成分析の構成要素

構成分析には次のコンポーネントが含まれます。

適切に設計されたステータス:: Well-Architected ステータスは、データベース構成の全体的な健全性を示します。構成は、「最適化済み」、「最適化されていない」、「過剰プロビジョニング」に分類されます。構成の well-architected ステータスは、Workload Factory コンソールの Microsoft SQL Server インスタンスまたは Oracle データベース内から参照されます。
適切に設計されたスコア:: スコアには現在分析されているすべての構成が含まれ、パーセンテージで表示されます。スコアが 25% の場合、データベース デプロイメントの 25% が適切に設計されていることを意味します。Well-Architected スコアは、*Well-Architected* 画面および Workload Factory コンソールの Microsoft SQL Server インスタンスまたは Oracle データベース内から参照されます。
構成のカテゴリ:: 構成は、ストレージ、コンピューティング、アプリケーション、復元力、クローン作成のカテゴリに分類されます。各カテゴリには、定期的に分析される特定の構成評価が含まれます。構成カテゴリは、*Well-architected* 画面および Workload Factory コンソールの Microsoft SQL Server インスタンスまたは Oracle データベース内から参照されます。




== 分析範囲

最適化の範囲は、評価するコンポーネントによって異なります。たとえば、ストレージの最適化はSQLインスタンスレベルで行われ、コンピューティングの最適化はホストレベルで行われます。



== 分析要件

完全なデータベース環境分析を行うには、リソースが登録され、オンラインになっている必要があります。

link:register-instance.html["リソースを登録する方法を学びます。"]

.次のステップ
link:optimize-configurations.html["適切に設計されたデータベース構成を実装する"]
