---
sidebar: sidebar 
permalink: postpone-analysis.html 
keywords: postpone configuration analysis, dismiss configuration analysis, postpone, dismiss, stop, optimization, Microsoft SQL Server, host, instance, FSx for ONTAP 
summary: 不要なアラートや不正確な最適化結果を回避するために、データベース環境に適用されない特定のデータベース構成の分析を延期または却下します。 
---
= データベース設定の分析を延期または却下する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
不要なアラートや不正確な最適化結果を回避するために、データベース環境に適用されない特定のデータベース構成の分析を延期または却下します。延期または却下された構成分析は、いつでも再アクティブ化できます。

.タスクの内容
データベース構成のアプリケーション要件は異なります。Workload Factoryには、特定のデータベース構成の分析を省略する2つのオプションがあります。これにより、関連する問題のみを監視し、関連する構成の健全性を正確に把握できます。特定の構成分析が延期または却下された場合、その構成は合計最適化スコアに含まれません。

構成レベルおよびSQL Serverインスタンスレベルで、構成分析の延期、却下、および再アクティブ化を行うことができます。

* * 30日間延期*：解析を延期すると、解析が30日間停止します。30日後、分析は自動的に再開されます。
* *却下*：解析を却下すると、解析が無期限に延期されます。必要に応じて解析を再開できます。


Microsoft SQL Serverインスタンスについては、次の設定を延期または却下できます。

* ストレージのサイジング：ストレージ階層、ファイルシステムのヘッドルーム、ログドライブのサイズ、tempdbドライブのサイズを含む
* ストレージレイアウト：ユーザデータファイルの配置、ログファイルの配置、tempdbの配置を含む
* ストレージ構成：容量管理、シンプロビジョニング、階層化ポリシー、Snapshot、マルチパスI/Oステータス、ポリシー、セッションなど
* コンピューティング：サイズ適正化、オペレーティングシステムのパッチ、受信側スケーリング（RSS）やTCPオフロードなどのネットワークアダプタ設定を含む
* アプリケーション：Microsoft SQL Serverライセンス、Microsoft SQL Serverパッチ、およびMAXDOP設定を含む
* 耐障害性：ローカルSnapshot、FSx for ONTAPバックアップ、リージョン間レプリケーション（CRR）など
* クローン


次の手順では、設定レベルで分析を延期、却下、または再アクティブ化する方法について説明します。特定のSQL Serverインスタンスについて次のタスクを実行するには、*[ダッシュボード]*タブからを開始します。

[role="tabbed-block"]
====
.延期
設定分析を30日間停止するように延期します。30日後、分析は自動的に再開されます。

--
.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. [Inventory]*タブで、[Postpone]の設定まで下にスクロールし、3ドットのメニューを選択して[* Postpone for 30 days]*を選択します。
. 「 * Continue * 」を選択します。


.結果
設定の分析が30日間停止します。

--
.却下
構成分析を無期限に停止するには、[却下]をクリックします。必要に応じて解析を再開できます。

--
.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. [Inventory]*タブで、閉じる構成まで下にスクロールし、3ドットのメニューを選択して、*[Dismiss]*を選択します。
. 「 * Continue * 」を選択します。


.結果
構成分析が停止します。

--
.再アクティブ化
延期または却下された構成分析をいつでも再アクティブ化できます。

--
.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. [Inventory]*タブで、再アクティブ化する構成まで下にスクロールし、3ドットのメニューを選択して[* Reactivate]*を選択します。
. 「 * Continue * 」を選択します。


.結果
構成分析が再アクティブ化され、毎日実行されます。

--
====