---
sidebar: sidebar 
permalink: protect-sql-server.html 
keywords: protect, server, Microsoft SQL Server, SQL Server, protect instance, protect database 
summary: Microsoft SQL Server インスタンスとデータベースを保護します。 
---
= Microsoft SQL Server ワークロードを保護する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory コンソールからNetApp Backup and Recovery を使用して、Microsoft SQL Server アプリケーション データを保護します。この統合により、ローカルプライマリAmazon FSx for NetApp ONTAP (FSx for ONTAP) ストレージ上のローカルスナップショットを使用してワークロードをバックアップし、セカンダリ FSx for ONTAPストレージにワークロードを複製するという保護目標を達成できます。



== タスクの内容

Workload Factory は、リソースの検出、前提条件の検証、Microsoft SQL Server 用プラグインの構成とインストールを自動化し、 NetApp Backup and Recovery によるワークロードの保護を準備します。このプラグインは、Microsoft SQL Server のワークロードを保護できるNetAppソフトウェアのホスト側コンポーネントです。

NetApp Backup and Recovery は、 NetApp SnapMirrorデータ レプリケーション テクノロジーを活用して、スナップショット コピーを作成し、それをバックアップの場所に転送することで、すべてのバックアップが完全に同期されるようにします。

バックアップとリカバリによる保護の詳細については、 link:https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-mssql-protect-overview.html["バックアップとリカバリによる Microsoft SQL ワークロードの保護の概要"^]。



== 開始する前に

バックアップとリカバリを使用して Microsoft SQL Server ワークロードを保護するには、次の要件を満たす必要があります。

* 環境が以下の要件を満たしていることを確認してください link:https://docs.netapp.com/us-en/data-services-backup-recovery/concept-start-prereq.html#microsoft-sql-server-workload-requirements["バックアップとリカバリのSQL Serverの要件"^]。
* link:https://docs.netapp.com/us-en/data-services-backup-recovery/concept-start-prereq.html#in-netapp-console["NetAppコンソールの要件をすべて満たす"^] 設定、IAM ロールの割り当て、コンソール エージェントのインストールなどが含まれます。


NetAppアカウントへの組織管理者アクセス権を持っている場合は、 `backup and recovery super admin`役割は自動的に割り当てられます<<NetAppバックアップとリカバリによる保護の準備,NetAppバックアップとリカバリによる保護の準備>>。

* コネクタのホスト解像度を設定する
+
データベースを検出するには、コネクタでホスト解決を設定する必要があります。ホストデバイスで、IPアドレスとホスト名のマッピングを `/etc/hosts`ファイル。

+
** link:https://docs.netapp.com/us-en/data-services-backup-recovery/br-start-licensing.html["NetAppバックアップおよびリカバリのライセンスを設定する"^]






== NetAppバックアップとリカバリによる保護の準備

NetApp Backup and Recovery を使用して Microsoft SQL Server リソースを保護するための準備プロセスを完了します。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. データベース メニューから、*インベントリ* を選択します。
. インベントリで、エンジンの種類として *Microsoft SQL Server* を選択します。
. 保護するインスタンスを見つけて、メニューから [保護] を選択します。
. プロンプトが表示されたら、管理者アクセス権を持つ Windows 資格情報を入力します。
+
保護のためにNetApp Backup and Recovery を使用するには、SQL Server インスタンスを Windows 資格情報を使用して Workload Factory に登録する必要があります。

. 複数のコンソール エージェントがアクティブで利用可能な場合は、ワークロードを登録して保護する *コンソール エージェント* を選択します。
. データ保護の準備として、Workload Factory は、Backup and Recovery に SQL Server リソースを自動的に登録し、Microsoft SQL Server 用プラグインを構成およびインストールし、SQL Server インスタンスを保護するための前提条件を満たすリソースを検出します。プロセスを開始するには、[*開始*] を選択します。
. 前提条件を満たしたら、[*リダイレクト*] を選択してバックアップとリカバリにアクセスします。


.次のステップ
バックアップとリカバリから、Microsoft SQL Server インスタンスとデータベースを保護するポリシーを作成します。

link:https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-policies-create.html["Microsoft SQL Server インスタンスとデータベースを保護するためのポリシーを作成する方法を学びます"^]。

関連情報については、 link:https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-mssql-protect-overview.html["バックアップとリカバリのドキュメント"^] Microsoft SQL Server のワークロードを管理します。
