---
sidebar: sidebar 
permalink: protect-sql-server.html 
keywords: protect, server, Microsoft SQL Server, SQL Server, protect instance, protect database 
summary: Microsoft SQL Server インスタンスとデータベースを保護します。 
---
= Microsoft SQL Server ワークロードを保護する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
ワークロード ファクトリー コンソールからBlueXP backup and recoveryを使用して、Microsoft SQL Server アプリケーション データを保護します。この統合により、ローカルプライマリAmazon FSx for NetApp ONTAP (FSx for ONTAP) ストレージ上のローカルスナップショットを使用してワークロードをバックアップし、セカンダリ FSx for ONTAPストレージにワークロードを複製するという保護目標を達成できます。



== タスクの内容

ワークロード ファクトリーは、インスタンスおよびデータベース リソースの検出、前提条件の検証、Microsoft SQL Server 用プラグインの構成とインストールのプロセスを自動化するのに役立ちます。これらはすべて、 BlueXP backup and recoveryを使用して Microsoft SQL Server ワークロードを保護するための準備プロセスの一部です。このプラグインは、Microsoft SQL Server のワークロードを保護できるNetAppソフトウェアのホスト側コンポーネントです。

BlueXP backup and recoveryは、 NetApp SnapMirrorデータ レプリケーション テクノロジーを活用して、スナップショット コピーを作成し、それをバックアップ場所に転送することで、すべてのバックアップが完全に同期されるようにします。

BlueXP backup and recoveryによる保護の詳細については、link:https://docs.netapp.com/us-en/bluexp-backup-recovery/br-use-mssql-protect-overview.html["BlueXP backup and recoveryによる Microsoft SQL ワークロードの保護の概要"^] 。



== 開始する前に

BlueXP backup and recoveryを使用して Microsoft SQL Server ワークロードの保護を開始するための要件は次のとおりです。

* BlueXPコネクタ
+
参照link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html["BlueXPコネクタの設定方法を学ぶ"^]そしてlink:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["標準BlueXP要件"^]。

+
コネクタには Ubuntu 22.04 LTS オペレーティング システムが必要です。

* BlueXP backup and recoveryのライセンス
+
link:https://docs.netapp.com/us-en/bluexp-backup-recovery/br-start-licensing.html["BlueXP backup and recoveryのライセンスを設定する"^]

* コネクタのホスト解像度の設定
+
データベースを検出するには、コネクタでホスト解決を設定する必要があります。ホストデバイスで、IPアドレスとホスト名のマッピングを `/etc/hosts`ファイル。





== BlueXP backup and recoveryで保護を準備する

BlueXP backup and recoveryを使用して Microsoft SQL Server リソースを保護するための準備プロセスを完了します。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. [データベース]で、*[インベントリ]*タブを選択します。
. *エンジン タイプ* を *Microsoft SQL Server* にフィルターします。
. 保護するインスタンスのメニューから*保護*を選択します。
. ワークロードを登録して保護する *コネクタ* を選択します。
. データ保護を準備するために、ワークロード ファクトリーは SQL Server リソースを BlueXP backup and recoveryに自動的に登録し、Microsoft SQL Server 用プラグインを構成およびインストールし、SQL Server インスタンスを保護するための前提条件を満たすリソースを検出します。プロセスを開始するには、[*開始*] を選択します。
. 前提条件が満たされたら、[リダイレクト] を選択してBlueXP backup and recoveryにリダイレクトします。


.次のステップ
BlueXP backup and recoveryから、Microsoft SQL Server インスタンスとデータベースを保護するためのポリシーを作成します。

link:https://docs.netapp.com/us-en/bluexp-backup-recovery/br-use-policies-create.html["Microsoft SQL Server インスタンスとデータベースを保護するためのポリシーを作成する方法を学びます"^] 。

関連情報については、link:https://docs.netapp.com/us-en/bluexp-backup-recovery/br-use-mssql-protect-overview.html["BlueXP backup and recoveryドキュメント"^] Microsoft SQL Server ワークロードを管理します。
