---
sidebar: sidebar 
permalink: register-instance.html 
keywords: manage, register, Microsoft SQL Server instance, Oracle database, manage database, manage instance 
summary: NetApp Workload Factory for Databases でリソースのステータス、リソース使用率、保護、ストレージ パフォーマンスを監視できるようにリソースを登録します。 
---
= NetApp Workload Factory for Databases にリソースを登録する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory for Databases でインスタンスとデータベースのステータス、リソース使用率、保護、ストレージ パフォーマンスを監視できるように、Microsoft SQL Server のインスタンスと Oracle のデータベースを登録します。

登録は、FSx for ONTAPファイル システム ストレージ上で実行されているデータベース エンジンに対してのみ可能です。



== タスクについて

インスタンス (SQL Server) またはデータベース (Oracle) の登録には、認証と準備の 2 つの手順が含まれます。準備として、すべての AWS、 NetApp、および PowerShell モジュールがインスタンスにインストールされていることを確認する必要があります。

SQL Server 資格情報または Windows 資格情報を使用して認証できます。


NOTE: Workload Factory は、Microsoft SQL Server インスタンスと Oracle データベースの登録と管理のみをサポートします。 Workload Factory で選択した AWS アカウントの認証情報に応じて、PostgreSQL ホストがインベントリに表示される場合があります。現在、Workload Factory は、Amazon Linux オペレーティングシステムでのみ実行されている未登録の PostgreSQL インスタンスをサポートしています。



== 開始する前に

インスタンスを登録する前に、次の点を考慮してください。

インスタンスまたはデータベースのホストがインベントリに表示されている必要があります。ホストをインベントリに表示するには、 link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["表示、計画、分析の権限を付与する"^] AWS アカウントで。



=== プライベートネットワークにインスタンスを登録する

外部接続のないプライベート ネットワークにインスタンス (SQL Server) またはデータベース (Oracle) を登録するには、SQL サーバーが存在するサブネットに関連付けられた次のエンドポイントが VPC で使用可能である必要があります。インターフェイス エンドポイントが、接続されたセキュリティ グループでポート 443 を許可していることを確認します。

* `S3 Gateway/endpoint`
* `ssm`
* `ssmmessages`
* `fsx`
+
EC2インスタンスからのすべてのアウトバウンド接続にプロキシサーバを使用する場合は、管理操作が機能するように、次のドメインへのアクセスを許可する必要があります。

* ``.microsoft.com``（SQLサーバー）
* ``.powershellgallery.com``（SQLサーバー）
* ``.aws.amazon.com``
* ``.amazonaws.com``




== SQL Server インスタンスを登録する

インスタンスの登録には、インスタンスの認証と準備が含まれます。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. データベース メニューから、*インベントリ* を選択します。
. インベントリで、エンジンの種類として *Microsoft SQL Server* を選択します。
. *インスタンス*タブを選択します。
. 単一のインスタンスを登録するか、複数のインスタンスを登録するかを選択します。
+
.. 単一インスタンスの登録: 管理するインスタンスに移動し、*インスタンスの登録*を選択します。
.. 複数インスタンスの登録: *複数インスタンスの登録* ボタンを選択します。
+
複数のインスタンスを登録するには、2つのオプションがあります。どちらの場合も、インスタンスは同じ認証ステータス（未認証または認証済み）を共有する必要があります。

+
*** 認証されていないインスタンス：登録する認証されていないインスタンスを複数選択してください。これらのインスタンスは、同じ認証資格情報とFSx for ONTAPの資格情報を共有する必要があります。「適用」を選択し、「次へ」を選択してください。
*** 認証済みインスタンス: 登録する複数の認証済みインスタンスを選択し、[次へ] を選択します。




. 「インスタンスの登録」ページのステップ2で、インスタンスの認証モードを選択し、以下の情報を入力して「次へ」を選択します。インスタンスが既に認証されている場合は、「次へ」を選択します。
+
** *SQL Server 認証*: SQL Server のユーザー名とパスワード、および FSx for ONTAP ファイル システムのユーザー名とパスワードを入力します。
** *Windows 認証*: Windows のユーザー名とパスワード、および FSx for ONTAP ファイル システムのユーザー名とパスワードを入力します。


. ステップ 3 では、インスタンスが必要な前提条件を満たしていることを確認してインスタンスを準備します。必要なモジュールがすべてインストールされ、前提条件を満たしている場合は、「次へ」を選択してインスタンスを登録してください。必要な操作が必要な場合は、以下の手順に従ってください。
+
.. 不足している場合は、ワークロード ファクトリを選択して、*不足している AWS および NetApp PowerShell モジュールをインストール*します。
.. 不足している場合は、ワークロードファクトリーを選択して*不足しているPowerShell 7をインストール*してください。不足しているPowerShellモジュール7をインストールするには、システムを再起動する必要があります。
.. 次の機能の前提条件リストを確認してください。インスタンスを登録するには、機能ごとにすべての前提条件を満たしていることを確認してください。
+
*** *適切に設計された問題と推奨事項を確認する*
*** *適切に設計された問題を修正*
*** *データベースを作成*
*** *データベースのコピーを作成する（サンドボックス）*
+
前提条件を完了するには、AWS IAM ポリシーのアクセス許可、EC2 IAM インスタンス プロファイルのアクセス許可、SQL Server のアクセス許可、および PowerShell モジュールの更新が含まれます。



.. 前提条件が完了し、チェックが*準備完了*になったら、インスタンスを*登録*することを選択できます。




.結果
インスタンスの登録が開始されます。進行状況を追跡するには、[*ジョブ監視*] タブを選択します。



== Oracleデータベースを登録する

データベースの登録には、インスタンスの認証と準備が含まれます。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. データベース メニューから、*インベントリ* を選択します。
. インベントリで、データベース エンジンとして *Oracle* を選択します。
. *データベース*タブを選択します。
. 単一のデータベースを登録するか、複数のデータベースを登録するかを選択します。
+
.. 単一データベースの登録: 管理するデータベースに移動し、*データベースの登録*を選択します。
.. 複数のデータベースの登録: *複数のデータベースを登録* ボタンを選択します。
+
複数のデータベースを登録するには 2 つのオプションがあります。どちらの場合も、データベースは同じ認証ステータス (認証なしまたは認証済み) を共有する必要があります。

+
*** 認証されていないデータベース: 登録する認証されていないデータベースを複数選択します。これらのデータベースは、同じ認証資格情報と FSx for ONTAP資格情報を共有する必要があります。  *適用*を選択し、*次へ*を選択します。
*** 認証済みデータベース: 登録する複数の認証済みデータベースを選択し、[次へ] を選択します。




. 「データベースの登録」ページのステップ 2 で、データベース認証モードを選択し、次の詳細を入力して、「次へ」を選択します。データベースがすでに認証されている場合は、[次へ] を選択します。
+
** *Oracle ユーザー認証*: Oracle ユーザー名とパスワード、および FSx for ONTAPファイル システムのユーザー名とパスワードを入力します。
** *Oracle ASM ユーザー認証*: オプション。  Oracle データベースで Automatic Storage Management (ASM) が使用されている場合は、Oracle ASM (グリッド) のユーザー名とパスワードを入力します。


. 手順 3 では、データベースが必要な前提条件を満たしていることを確認して、データベースを準備します。必要なモジュールがすべてインストールされ、前提条件が満たされている場合は、[次へ] を選択してデータベースを登録します。アクションを実行する必要があるときは、次の手順に従ってください。
+
.. 次の機能の前提条件リストを確認してください。データベースを登録するには、単一の機能のすべての前提条件が完了している必要があります。
+
*** *適切に設計された問題と推奨事項を確認する*


.. 次の前提条件を完了してください。
+
*** *AWS IAM ポリシーのアクセス許可*: AWS コンソールで AWS アクセス許可をコピーおよび更新します。
*** *EC2 IAM インスタンスプロファイルの権限*: AWS コンソールで、Amazon EC2 インスタンスの EC2 IAM インスタンスプロファイルの権限をコピーして更新します。
*** *デプロイメント モジュール*: 必要に応じて、AWS コマンドライン インターフェイス (AWS CLI)、jq (コマンドライン JSON プロセッサ)、Python 3.12 (バージョン 3.6 以上がまだインストールされていない場合) などの依存モジュールをインストールするように選択します。ワークロード ファクトリーは、登録プロセスの一環としてこれらのモジュールを自動的にインストールします。
*** *Oracle ユーザーの権限*: 必要に応じて、Oracle ユーザーの権限を更新します。


.. 前提条件が完了し、チェックが*準備完了*になったら、データベースの*登録*を選択できます。




.結果
データベースの登録が開始されます。進行状況を追跡するには、[*ジョブ監視*] タブを選択します。

.次のステップ
リソース登録後、次のタスクを実行できます。

* インベントリからデータベースを表示する
* link:create-database.html["データベースの作成"]
* link:create-sandbox-clone.html["データベースクローン（サンドボックス）を作成する"]
* link:optimize-configurations.html["適切に設計されたデータベース構成を実装する"]

