---
sidebar: sidebar 
permalink: register-instance.html 
keywords: Microsoft SQL Server instance, PostgreSQL server instance, Oracle host instance, manage host, view host, database host, database instance, manage, unregister 
summary: データベース用のBlueXP  ワークロードファクトリでMicrosoft SQL Serverインスタンスを管理します。 
---
= データベースのワークロードファクトリーにインスタンスを登録する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
ホスト インスタンスを登録すると、データベースのワークロード ファクトリでインスタンスとデータベースのステータス、リソース使用率、保護、ストレージ パフォーマンスを監視できるようになります。

データベースは、FSx for ONTAP ファイル システム ストレージにのみインスタンスを登録できます。



== タスクについて

ホスト インスタンスの登録には、インスタンスの認証と、すべての AWS、NetApp、および PowerShell モジュールがインスタンスにインストールされていることを確認してインスタンスを準備するという 2 つの手順が含まれます。

SQL Server 資格情報または Windows 資格情報を使用してリンクを認証できます。


NOTE: ワークロードファクトリーは、Microsoft SQL Server ホストインスタンスの登録と管理のみをサポートしています。ワークロードファクトリーで選択した AWS アカウントの認証情報によっては、PostgreSQL および Oracle ホストがインベントリに表示される場合があります。現在、ワークロードファクトリーは、Amazon Linux オペレーティングシステムでのみ実行されている未登録の PostgreSQL インスタンスと、Red Hat Enterprise Linux でのみ実行されている Oracle インスタンスをサポートしています。



== プライベートネットワークにホストインスタンスを登録する

外部接続のないプライベート ネットワークにホスト インスタンスを登録するには、SQL サーバーが存在するサブネットに関連付けられた次のエンドポイントが VPC で使用可能である必要があります。接続されているセキュリティグループのポート443が、インターフェイスエンドポイントで許可されていることを確認します。

* `S3 Gateway/endpoint`
* `ssm`
* `ssmmessages`
* `fsx`


EC2インスタンスからのすべてのアウトバウンド接続にプロキシサーバを使用する場合は、管理操作が機能するように、次のドメインへのアクセスを許可する必要があります。

* ``.microsoft.com``
* ``.powershellgallery.com``
* ``.aws.amazon.com``
* ``.amazonaws.com``




== 開始する前に

インスタンスのホストはインベントリタブに表示されている必要があります。ホストがインベントリに表示されるには、 link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWSアカウントの認証情報と_読み取り専用_または_読み取り/書き込み_モードの権限を追加する必要があります"^] 。



== ホストインスタンスを登録する

ホスト インスタンスの登録には、インスタンスの認証と準備が含まれます。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[データベースインベントリに移動]*を選択します。
. [データベース]で、*[インベントリ]*タブを選択します。
. [インベントリ] タブで、[インスタンス] タブを選択します。
. 管理するインスタンスに移動し、*インスタンスの登録*を選択します。
. [インスタンスの登録] ページで、SQL Server のユーザー名とパスワード、および FSx for ONTAP ファイル システムのユーザー名とパスワードを入力します。
. 「 * 次へ * 」を選択します。
. インスタンスが必要な前提条件を満たしていることを確認し、準備を整えてください。必要なモジュールがすべてインストールされ、前提条件を満たしている場合は、「次へ」を選択してインスタンスを登録してください。必要な操作が必要な場合は、以下の手順に従ってください。
+
.. 不足している場合は、ワークロード ファクトリを選択して、*不足している AWS および NetApp PowerShell モジュールをインストール*します。
.. 不足している場合は、ワークロードファクトリーを選択して*不足しているPowerShell 7をインストール*してください。不足しているPowerShellモジュール7をインストールするには、システムを再起動する必要があります。
.. 以下の機能の前提条件リストを確認してください。インスタンスを登録するには、1つの前提条件を満たしている必要があります。
+
*** *適切に設計された問題と推奨事項を確認する*
*** *適切に設計された問題を修正*
*** *データベースを作成*
*** *データベースのコピーを作成する（サンドボックス）*
+
前提条件を完了するには、AWS IAM ポリシーのアクセス許可、EC2 IAM インスタンス プロファイルのアクセス許可、SQL Server のアクセス許可、および PowerShell モジュールの更新が含まれます。



.. 続行するには、不足している前提条件を少なくとも 1 つ完了してください。
.. 1 つ以上の前提条件が完了し、チェックが *準備完了* になったら、インスタンスを *登録* することを選択できます。




.結果
インスタンス登録リクエストが開始されます。進行状況を追跡するには、「ジョブ監視」タブを選択してください。
